Repository palantir/dialogue, pull requests merged in 2020-03, with the labels that each got.

#459 Fork DeterministicScheduler to support nanoseconds
  simulation/src/main/java/com/palantir/dialogue/core/ExternalDeterministicScheduler.java
  simulation/src/main/java/com/palantir/dialogue/core/NanosecondPrecisionDeterministicScheduler.java
  simulation/src/main/java/com/palantir/dialogue/core/Simulation.java
  simulation/src/main/java/com/palantir/dialogue/core/TestCaffeineTicker.java
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/simplest_possible_case[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/drastic_slowdown[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_big_spike[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/simplest_possible_case[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/simplest_possible_case[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].txt
Labels: merge when ready, no changelog

#458 Interrupted calls properly close resources
  changelog/@unreleased/pr-458.v2.yml
  dialogue-target/src/main/java/com/palantir/dialogue/RemoteExceptions.java
  dialogue-target/src/test/java/com/palantir/dialogue/RemoteExceptionsTest.java
Labels: autorelease, merge when ready

#475 Migrate some logic from generated code into the runtime library
  .palantir/revapi.yml
  changelog/@unreleased/pr-475.v2.yml
  dialogue-example/src/main/java/com/palantir/dialogue/example/SampleServiceClient.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultConjureRuntime.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/Clients.java
  dialogue-target/src/main/java/com/palantir/dialogue/ConjureRuntime.java
Labels: autorelease, merge when ready

#474 Remove workaround for a resolved jackson cbor bug
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/Encodings.java
Labels: merge when ready, no changelog

#473 fix #389: DefaultErrorDecoder handles types with parameters
  changelog/@unreleased/pr-473.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultErrorDecoder.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/Encodings.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultErrorDecoderTest.java
Labels: autorelease, merge when ready

#477 fix #413: Remove RemoteExceptions utility
  .palantir/revapi.yml
  changelog/@unreleased/pr-477.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsBlockingTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/RemoteExceptions.java
Labels: merge when ready

#476 use generated clients in test
  .gitignore
  build.gradle
  dialogue-client-test-lib/build.gradle
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractSampleServiceClientTest.java
  dialogue-example/build.gradle
  dialogue-example/dialogue-example-dialogue/.gitignore
  dialogue-example/dialogue-example-objects/.gitignore
  dialogue-example/src/main/conjure/example.yml
  dialogue-example/src/main/java/com/palantir/dialogue/example/AsyncSampleService.java
  dialogue-example/src/main/java/com/palantir/dialogue/example/SampleObject.java
  dialogue-example/src/main/java/com/palantir/dialogue/example/SampleService.java
  dialogue-example/src/main/java/com/palantir/dialogue/example/SampleServiceClient.java
  dialogue-java-client/src/test/java/com/palantir/dialogue/HttpSampleServiceClientTest.java
  dialogue-okhttp-client/src/test/java/com/palantir/dialogue/OkHttpSampleServiceClientTest.java
  dialogue-target/build.gradle
  settings.gradle
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#479 Remove unused methods from PlainSerDe
  .palantir/revapi.yml
  changelog/@unreleased/pr-479.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjurePlainSerDe.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/PlainSerDeTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/PlainSerDe.java
Labels: merge when ready

#480 Remove unnecessary header constants from the target api
  .palantir/revapi.yml
  changelog/@unreleased/pr-480.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientBlockingChannel.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractSampleServiceClientTest.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoder.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDeTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoderTest.java
  dialogue-serde/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  dialogue-target/src/main/java/com/palantir/dialogue/EmptyBody.java
  dialogue-target/src/main/java/com/palantir/dialogue/ErrorDecoder.java
  dialogue-target/src/main/java/com/palantir/dialogue/Headers.java
  dialogue-target/src/test/java/com/palantir/dialogue/EmptyBodyTest.java
Labels: autorelease, merge when ready

#482 fixes #468: Dialogue clients send Accept headers
  .palantir/revapi.yml
  changelog/@unreleased/pr-482.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/BinaryEncoding.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/BodySerDe.java
  dialogue-target/src/main/java/com/palantir/dialogue/Deserializer.java
Labels: autorelease, merge when ready

#484 Remove the arbitrary FixedLimitedChannel
  changelog/@unreleased/pr-484.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/FixedLimitedChannelTest.java
  simulation/src/test/resources/one_big_spike[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/txt/one_big_spike[UNLIMITED_ROUND_ROBIN].txt
Labels: autorelease, merge when ready

#485 instrument retrying channels scheduled executor service
  changelog/@unreleased/pr-485.v2.yml
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#483 Dialogue Response headers are represented using a multimap
  .palantir/revapi.yml
  changelog/@unreleased/pr-483.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientBlockingChannel.java
  dialogue-blocking-channels/src/test/java/com/palantir/dialogue/blocking/BlockingChannelAdapterTest.java
  dialogue-client-test-lib/build.gradle
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ContentDecodingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ContentDecodingChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
  dialogue-httpurlconnection-client/src/main/java/com/palantir/dialogue/httpurlconnection/HttpUrlConnectionBlockingChannel.java
  dialogue-java-client/src/main/java/com/palantir/dialogue/HttpChannel.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpResponse.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDeTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoderTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/Response.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationUtils.java
  versions.lock
Labels: autorelease, merge when ready

#486 Report metrics for in-flight requests
  changelog/@unreleased/pr-486.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ActiveRequestInstrumentationChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/ActiveRequestInstrumentationChannelTest.java
Labels: autorelease, merge when ready

#489 Remove stopgap components from circular generator dependency upgrade
  .palantir/revapi.yml
  changelog/@unreleased/pr-489.v2.yml
  dialogue-target/src/main/java/com/palantir/dialogue/BodySerDe.java
  dialogue-target/src/main/java/com/palantir/dialogue/Deserializer.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#491 Regenerate simulation data with current metrics
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/all_nodes_500[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/simplest_possible_case[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[UNLIMITED_ROUND_ROBIN].png
Labels: merge when ready, no changelog

#493 Support weighted encodings
  changelog/@unreleased/pr-493.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultConjureRuntime.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/WeightedEncoding.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDeTest.java
Labels: autorelease, merge when ready

#494 Replace slf4j-simple with log4j2 for tests
  dialogue-core/build.gradle
  dialogue-core/src/test/resources/log4j2-test.xml
  simulation/build.gradle
  simulation/src/test/resources/log4j2-test.xml
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#492 Support live reloading uris
  .palantir/revapi.yml
  changelog/@unreleased/pr-492.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ChannelFactory.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelsTest.java
  dialogue-core/src/test/resources/tracing/ChannelsTest/traces_on_succes.log
  dialogue-core/src/test/resources/tracing/DialogueChannelsTest/traces_on_retries.log
  dialogue-core/src/test/resources/tracing/DialogueChannelsTest/traces_on_success.log
  dialogue-httpurlconnection-client/src/main/java/com/palantir/dialogue/httpurlconnection/HttpUrlConnectionChannels.java
  dialogue-java-client/src/main/java/com/palantir/dialogue/JavaChannels.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannels.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/simplest_possible_case[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/black_hole[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/simplest_possible_case[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/simplest_possible_case[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].txt
Labels: autorelease, merge when ready

#497 handle uri removal in pin until error update
  changelog/@unreleased/pr-497.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorChannelTest.java
Labels: autorelease, merge when ready

#498 Apache client connection pool instrumentation
  changelog/@unreleased/pr-457.v2.yml
  dialogue-apache-hc4-client/build.gradle
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheClientGauges.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/TestConfigurations.java
Labels: autorelease, merge when ready

#499 Properly support optional empty response
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/TypeMarkers.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDeTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/TypeMarkersTest.java
Labels: autorelease, merge when ready

#500 improve error on supported 204 type
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
Labels: autorelease, merge when ready, no changelog

#501 Dialogue supports optional binary responses
  .palantir/revapi.yml
  changelog/@unreleased/pr-501.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/BinaryEncoding.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDeTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/BodySerDe.java
Labels: autorelease, merge when ready

#505 Dialogue closes optional closeables on interruption
  changelog/@unreleased/pr-505.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsBlockingTest.java
Labels: autorelease, merge when ready

#506 Setup verifier
  dialogue-client-test-lib/build.gradle
  dialogue-client-verifier/build.gradle
  dialogue-client-verifier/src/test/java/com/palantir/verification/AutoDeserializeTest.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/Cases.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/SingleParamServicesTest.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/VerificationClients.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/VerificationServerRule.java
  dialogue-client-verifier/src/test/resources/ignored-test-cases.yml
  dialogue-client-verifier/src/test/resources/log4j2-test.xml
  dialogue-client-verifier/verification-server-api/.gitignore
  settings.gradle
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#507 Upgrade the generator to fix binary alias handling
  dialogue-client-verifier/src/test/resources/ignored-test-cases.yml
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#513 Concurrency Limits decrease in response to 429, 503 and 500s
  changelog/@unreleased/pr-513.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
Labels: autorelease, merge when ready

#514 fix #510: Use random selection over round robin
  changelog/@unreleased/pr-514.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RandomSelectionChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RoundRobinChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RandomSelectionChannelIndexTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RandomSelectionChannelTest.java
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/simplest_possible_case[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/black_hole[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/drastic_slowdown[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_500s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_500s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_big_spike[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/simplest_possible_case[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/simplest_possible_case[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/uncommon_flakes[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/uncommon_flakes[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[UNLIMITED_ROUND_ROBIN].png
Labels: autorelease, merge when ready

#518 Upgrade to fixed version of apache httpclient, resume auto-upgrades
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#516 Ressurect QueuedChannel
  changelog/@unreleased/pr-516.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BlacklistingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/LimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/BlacklistingChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
Labels: merge when ready

#515 Pin until error only switches on errors
  changelog/@unreleased/pr-515.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorChannel.java
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
Labels: autorelease, merge when ready

#521 Responses.isTooManyRequests is private
  dialogue-core/src/main/java/com/palantir/dialogue/core/Responses.java
Labels: merge when ready, no changelog

#522 ConcurrencyLimitedChannel has no maximum limit value
  changelog/@unreleased/pr-522.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
Labels: autorelease, merge when ready

#525 fix #328 Prevent request body resources from leaking
  .palantir/revapi.yml
  changelog/@unreleased/pr-525.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientBlockingChannel.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractProxyConfigTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/BinaryRequestBody.java
  dialogue-target/src/main/java/com/palantir/dialogue/RequestBody.java
Labels: autorelease, merge when ready

#524 Instrument channels with channel name
  changelog/@unreleased/pr-524.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ActiveRequestInstrumentationChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueFutures.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/InstrumentedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/ActiveRequestInstrumentationChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelsTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/InstrumentedChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
  dialogue-httpurlconnection-client/src/main/java/com/palantir/dialogue/httpurlconnection/HttpUrlConnectionChannels.java
  dialogue-java-client/src/main/java/com/palantir/dialogue/JavaChannels.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannels.java
  simulation/src/main/java/com/palantir/dialogue/core/Benchmark.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationUtils.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/all_nodes_500[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/simplest_possible_case[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[UNLIMITED_ROUND_ROBIN].png
Labels: autorelease, merge when ready

#530 Response metrics include service name
  changelog/@unreleased/pr-530.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/InstrumentedChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/InstrumentedChannelTest.java
  simulation/src/main/java/com/palantir/dialogue/core/Benchmark.java
Labels: autorelease, merge when ready

#534 Record metrics describing time spent queued
  changelog/@unreleased/pr-534.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
Labels: autorelease, merge when ready

#443 Instrument ConcurrencyLimitedChannel
  changelog/@unreleased/pr-443.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
Labels: autorelease, merge when ready

#535 [stacked] Keep track of apache connection pool metrics using WeakSummingGauge
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheClientGauges.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/WeakSummingGauge.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/WeakSummingGaugeTest.java
Labels: merge when ready, no changelog

#531 Tag connection pool metrics by channel name
  changelog/@unreleased/pr-531.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheClientGauges.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/WeakSummingGauge.java
  dialogue-apache-hc4-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/WeakSummingGaugeTest.java
Labels: autorelease, merge when ready

#537 Fix SimulationTest graphs
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/all_nodes_500[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/simplest_possible_case[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[UNLIMITED_ROUND_ROBIN].png
Labels: merge when ready, no changelog

#538 Dialogue avoids wrapping all runtime exceptions for cleaner results
  changelog/@unreleased/pr-538.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsBlockingTest.java
Labels: autorelease, merge when ready

#542 Instrument client TLS handshakes
  changelog/@unreleased/pr-542.v2.yml
  dialogue-apache-hc4-client/build.gradle
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
Labels: merge when ready

#543 Tag concurrency-limiter metrics with the channel name
  changelog/@unreleased/pr-543.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
Labels: autorelease, merge when ready

#548 BinaryRequestBody: fix confusing variable names/comments
  dialogue-target/src/main/java/com/palantir/dialogue/BinaryRequestBody.java
Labels: merge when ready, no changelog

#545 Implement a LeakDetectingChannel to notify when responses are leaked
  changelog/@unreleased/pr-545.v2.yml
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/LeakDetectingChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelsTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/LeakDetectingChannelTest.java
Labels: autorelease, merge when ready

#554 Response leak detection samples 1% of requests (down from 100%)
  changelog/@unreleased/pr-554.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/LeakDetectingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/LeakDetectingChannelTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
Labels: autorelease, merge when ready

#555 Stop publishing alternative channel impls (in prep for 1.0)
  dialogue-httpurlconnection-client/build.gradle
  dialogue-java-client/build.gradle
  dialogue-okhttp-client/build.gradle
Labels: merge when ready, no changelog

#556 Validate ciphers against the provided socket factory
  changelog/@unreleased/pr-556.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
Labels: autorelease, merge when ready

#559 Fill out the README a little
  README.md
Labels: merge when ready, no changelog

#560 dialogue.pinuntilerror tagged by channel-name
  changelog/@unreleased/pr-560.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorChannelTest.java
Labels: autorelease, merge when ready

#563 Support HTTP PATCH
  changelog/@unreleased/pr-563.v2.yml
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannel.java
  dialogue-target/src/main/java/com/palantir/dialogue/HttpMethod.java
Labels: autorelease, merge when ready

#561 ApacheHttpClientChannels logs client names with cipher suites
  changelog/@unreleased/pr-561.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
Labels: merge when ready

#564 Responses are no longer leaked when blocking channel futures are interrupted
  changelog/@unreleased/pr-564.v2.yml
  dialogue-apache-hc4-client/build.gradle
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ResponseLeakDetector.java
  dialogue-apache-hc4-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ResponseLeakDetectorTest.java
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/BlockingChannelAdapter.java
  dialogue-blocking-channels/src/test/java/com/palantir/dialogue/blocking/BlockingChannelAdapterTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ResponseLeakDetector.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
Labels: autorelease, merge when ready

#571 Some helpful toStrings for debugging
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/BinaryEncoding.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/Encoding.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/Encodings.java
Labels: merge when ready, no changelog

#572 Escape plus sign in query strings
  changelog/@unreleased/pr-572.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BaseUrl.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/UrlBuilderTest.java
Labels: autorelease, merge when ready

#570 Return unclosed InputStreams for binary and optional<binary> endpoints
  changelog/@unreleased/pr-570.v2.yml
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/CloseRecordingInputStream.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/TestResponse.java
  dialogue-client-verifier/build.gradle
  dialogue-client-verifier/src/test/java/com/palantir/verification/BinaryReturnTypeTest.java
  dialogue-example/src/main/conjure/example.yml
  dialogue-serde/build.gradle
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/BinaryEncoding.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultConjureRuntime.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/Encoding.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/Encodings.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/BinaryEncodingTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDeTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/Deserializer.java
  dialogue-target/src/main/java/com/palantir/dialogue/Response.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#582 Top level span provides information about the request being made
  changelog/@unreleased/pr-582.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueTracedRequestChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TraceEnrichingChannel.java
  dialogue-core/src/test/resources/tracing/DialogueChannelsTest/traces_on_retries.log
  dialogue-core/src/test/resources/tracing/DialogueChannelsTest/traces_on_success.log
  dialogue-core/src/test/resources/tracing/QueuedChannelTest/testQueueTracing.log
Labels: autorelease, merge when ready

#583 Migrate to junit 5
  dialogue-apache-hc4-client/build.gradle
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ResponseLeakDetectorTest.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/WeakSummingGaugeTest.java
  dialogue-blocking-channels/build.gradle
  dialogue-blocking-channels/src/test/java/com/palantir/dialogue/blocking/BlockingChannelAdapterTest.java
  dialogue-client-test-lib/build.gradle
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractProxyConfigTest.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractSampleServiceClientTest.java
  dialogue-java-client/build.gradle
  dialogue-java-client/src/test/java/com/palantir/dialogue/CompletableToListenableFutureTest.java
  dialogue-java-client/src/test/java/com/palantir/dialogue/HttpSampleServiceClientTest.java
  dialogue-okhttp-client/build.gradle
  dialogue-okhttp-client/src/test/java/com/palantir/dialogue/OkHttpSampleServiceClientTest.java
  dialogue-okhttp-client/src/test/java/com/palantir/dialogue/UrlsTest.java
  dialogue-serde/build.gradle
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/BinaryEncodingTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDeTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsBlockingTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/EncodingsTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoderTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/PlainSerDeTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/TypeMarkersTest.java
  dialogue-target/build.gradle
  dialogue-target/src/test/java/com/palantir/dialogue/RequestTest.java
  versions.lock
Labels: autorelease, merge when ready, no changelog

#585 Provide a tracing operation name to the blocking adapter executor
  changelog/@unreleased/pr-585.v2.yml
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/BlockingChannelAdapter.java
Labels: merge when ready

#588 don't autorelease test-only changes
  .github/autolabeler.yml
Labels: merge when ready, no changelog

#593 Refactor optional deserialization to avoid memoization
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/EmptyContainerDeserializer.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/JacksonEmptyContainerLoader.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/JacksonEmptyContainerLoaderTest.java
Labels: autorelease

#591 Upgrade netflix concurrency limits
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#597 CircleCI: do everything in one job
  .circleci/config.yml
Labels: merge when ready, no changelog

#576 Http 204 and alias of optional
  changelog/@unreleased/pr-576.v2.yml
  dialogue-client-verifier/src/test/java/com/palantir/verification/IntegrationTest.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/VerificationServerRule.java
  dialogue-client-verifier/src/test/resources/ignored-test-cases.yml
  dialogue-example/src/main/conjure/example.yml
  dialogue-serde/build.gradle
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultConjureRuntime.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/EmptyContainerDeserializer.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/Encodings.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/JacksonEmptyContainerLoader.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/BinaryEncodingTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDeTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/JacksonEmptyContainerLoaderTest.java
  versions.props
Labels: autorelease, merge when ready

#603 Delete dead code
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/TypeMarkers.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/TypeMarkersTest.java
Labels: merge when ready, no changelog

#584 client produces outgoing span
  changelog/@unreleased/pr-584.v2.yml
  dialogue-apache-hc4-client/src/test/resources/tracing/ApacheHttpClientChannelsTest/requestAreTraced.log
  dialogue-client-test-lib/build.gradle
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TraceEnrichingChannel.java
  dialogue-core/src/test/resources/tracing/DialogueChannelsTest/traces_on_retries.log
  dialogue-core/src/test/resources/tracing/DialogueChannelsTest/traces_on_success.log
  dialogue-core/src/test/resources/tracing/QueuedChannelTest/testQueueTracing.log
  dialogue-java-client/src/test/resources/tracing/JavaChannelsTest/requestAreTraced.log
  dialogue-okhttp-client/src/test/resources/tracing/OkHttpChannelTest/requestAreTraced.log
Labels: autorelease, merge when ready

#605 Live reloading an extra uri allows QueuedChannel to make progress
  changelog/@unreleased/pr-605.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelsTest.java
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
Labels: autorelease, merge when ready

#606 Logging around zero uri behaviour
  changelog/@unreleased/pr-606.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
Labels: autorelease, merge when ready
