Repository palantir/dialogue, pull requests merged in 2020-11, with the labels that each got.

#1048 Support behaviour changes based on URIs with a 'mesh-' prefix
  changelog/@unreleased/pr-1048.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Config.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/MeshMode.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TracedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/MeshModeTest.java
Labels: merge when ready

#1054 Test coverage for PathTemplates with empty string variables
  dialogue-core/src/test/java/com/palantir/dialogue/core/PathTemplateTest.java
Labels: merge when ready, no changelog

#1067 Reduce the client TLS session cache size
  changelog/@unreleased/pr-1067.v2.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/AugmentClientConfig.java
Labels: autorelease, merge when ready

#1069 Fix metric schema comment typo
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
Labels: merge when ready, no changelog

#1070 Log httpclient creation location when debug logging is enabled
  changelog/@unreleased/pr-1070.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelCache.java
Labels: autorelease, merge when ready
