Repository palantir/dialogue, pull requests merged in 2020-04, with the labels that each got.

#608 Apache client idle and validation timeouts scale with socket timeouts
  changelog/@unreleased/pr-608.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
Labels: autorelease, merge when ready

#610 --continue on CircleCI
  .circleci/config.yml
Labels: merge when ready, no changelog

#599 Defer expensive ObjectReader/ObjectWriter creation
  changelog/@unreleased/pr-599.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/LazilyInitializedEncoding.java
Labels: autorelease, merge when ready

#619 Implement support for HEAD requests
  changelog/@unreleased/pr-619.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientBlockingChannel.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-httpurlconnection-client/src/main/java/com/palantir/dialogue/httpurlconnection/HttpUrlConnectionBlockingChannel.java
  dialogue-java-client/src/main/java/com/palantir/dialogue/HttpChannel.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannel.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpResponse.java
  dialogue-target/src/main/java/com/palantir/dialogue/HttpMethod.java
Labels: autorelease, merge when ready

#621 [test-only] Always use TestResponse
  dialogue-apache-hc4-client/build.gradle
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
  dialogue-blocking-channels/build.gradle
  dialogue-blocking-channels/src/test/java/com/palantir/dialogue/blocking/BlockingChannelAdapterTest.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/VerificationServerRule.java
  dialogue-core/build.gradle
  dialogue-core/src/test/java/com/palantir/dialogue/core/ActiveRequestInstrumentationChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ContentDecodingChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelsTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/UserAgentChannelTest.java
  dialogue-core/src/test/resources/tracing/DialogueChannelsTest/traces_on_retries.log
  dialogue-core/src/test/resources/tracing/DialogueChannelsTest/traces_on_success.log
  dialogue-httpurlconnection-client/build.gradle
  dialogue-java-client/build.gradle
  dialogue-okhttp-client/build.gradle
  dialogue-serde/build.gradle
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoderTest.java
  dialogue-test-common/build.gradle
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractProxyConfigTest.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractSampleServiceClientTest.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/CloseRecordingInputStream.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/TestConfigurations.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/TestEndpoint.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/TestResponse.java
  dialogue-test-common/src/main/resources/keyStore.jks
  dialogue-test-common/src/main/resources/mockito-extensions/org.mockito.plugins.MockMaker
  dialogue-test-common/src/main/resources/trustStore.jks
  settings.gradle
  simulation/build.gradle
  simulation/src/main/java/com/palantir/dialogue/core/SimulationServer.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationUtils.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
Labels: merge when ready, no changelog

#625 Nicer error when queue is full
  changelog/@unreleased/pr-625.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/LimitedChannelToChannelAdapter.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
Labels: autorelease, merge when ready

#628 maxQueueSize 1k -> 100k
  changelog/@unreleased/pr-628.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
Labels: autorelease, merge when ready

#630 Fix deserialization of structured errors after retries are exhausted
  changelog/@unreleased/pr-630.v2.yml
  dialogue-client-verifier/src/test/java/com/palantir/verification/IntegrationTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
Labels: autorelease, merge when ready

#631 Fix PinUntilError to start on a random channel
  changelog/@unreleased/pr-631.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelsTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorChannelTest.java
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
Labels: autorelease, merge when ready

#632 [test-only] Simulations no longer have 10 identical clients
  dialogue-core/src/main/java/com/palantir/dialogue/core/NeverThrowChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorChannel.java
  simulation/src/main/java/com/palantir/dialogue/core/Simulation.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/simplest_possible_case[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/black_hole[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/drastic_slowdown[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/fast_500s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_500s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/simplest_possible_case[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/simplest_possible_case[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/uncommon_flakes[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/uncommon_flakes[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/uncommon_flakes[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[UNLIMITED_ROUND_ROBIN].png
Labels: merge when ready, no changelog

#633 Implement QosException mapping
  changelog/@unreleased/pr-633.v2.yml
  dialogue-client-verifier/src/test/java/com/palantir/verification/IntegrationTest.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoder.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoderTest.java
Labels: autorelease, merge when ready

#639 Sentence explaining pin until error decision
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorChannel.java
Labels: no changelog

#638 Remove the windowed limit from the Dialogue concurrency limiter configuration
  changelog/@unreleased/pr-638.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_500s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
Labels: autorelease, merge when ready

#641 Simpler AIMD implementation
  changelog/@unreleased/pr-641.v2.yml
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#643 Instrument the BlockingChannelAdapter ThreadFactory
  changelog/@unreleased/pr-643.v2.yml
  dialogue-blocking-channels/build.gradle
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/BlockingChannelAdapter.java
Labels: autorelease, merge when ready

#645 IOExceptions push back concurrency limits
  changelog/@unreleased/pr-645.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
Labels: autorelease, merge when ready

#642 The dialogue apache client executor is configurable
  changelog/@unreleased/pr-642.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ResponseLeakDetector.java
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/BlockingChannelAdapter.java
  dialogue-blocking-channels/src/test/java/com/palantir/dialogue/blocking/BlockingChannelAdapterTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ResponseLeakDetector.java
Labels: autorelease, merge when ready

#629 Retry GET & HEAD requests on server 500s
  changelog/@unreleased/pr-629.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationUtils.java
  simulation/src/test/resources/all_nodes_500[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[UNLIMITED_ROUND_ROBIN].png
Labels: autorelease, merge when ready

#644 RetryingChannel retries IOExceptions rather than all Throwables
  changelog/@unreleased/pr-644.v2.yml
  dialogue-client-verifier/src/test/java/com/palantir/verification/IntegrationTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelsTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
Labels: autorelease, merge when ready

#646 [test-only] One simulation uses a GET endpoint
  simulation/src/main/java/com/palantir/dialogue/core/Benchmark.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationUtils.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].txt
Labels: merge when ready, no changelog

#568 RetryingChannel records stacktraces for logs (when debug logging is enabled)
  changelog/@unreleased/pr-568.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
Labels: autorelease, merge when ready

#648 Implement naive 308 retry-other handling
  changelog/@unreleased/pr-648.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/Responses.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
Labels: autorelease, merge when ready

#651 Add tests for AimdConcurrencyLimiter; rename Listener to Token
  dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/AimdConcurrencyLimiterTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
Labels: merge when ready, no changelog

#650 Slightly more info from logging & metrics
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/BlockingChannelAdapter.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
Labels: merge when ready, no changelog

#652 Retrying executor ThreadFacotory instrumentation
  changelog/@unreleased/pr-652.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
Labels: autorelease, merge when ready

#655 More logging around Apache client creation & close
  changelog/@unreleased/pr-655.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
Labels: autorelease, merge when ready

#654 Delete low-signal `dialogue.concurrencylimiter.utilization` metric
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
Labels: merge when ready, no changelog

#658 Safe-logging exceptions are thrown on requests when the apache client is closed
  changelog/@unreleased/pr-658.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/SafeLoggingHttpClientConnectionManager.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
Labels: autorelease, merge when ready

#659 More SafeArgs when retries exhausted
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
Labels: merge when ready, no changelog

#661 PinUntilErrorChannel doesn't switch on 429
  changelog/@unreleased/pr-661.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorChannelTest.java
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
Labels: autorelease, merge when ready

#662 Rename `dialogue.client.response` metric to `client.response`
  changelog/@unreleased/pr-662-pt2.v2.yml
  changelog/@unreleased/pr-662.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DeprecationWarningChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/InstrumentedChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/InstrumentedChannelTest.java
  simulation/src/main/java/com/palantir/dialogue/core/Benchmark.java
Labels: autorelease, merge when ready

#663 Fail reasonably with zero uris rather than IndexOutOfBounds
  changelog/@unreleased/pr-663.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ZeroUriChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelsTest.java
Labels: autorelease, merge when ready

#664 The ZeroUriChannel provides additional context for failures
  changelog/@unreleased/pr-664.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ZeroUriChannel.java
Labels: autorelease, merge when ready

#665 Add documentation/annotations describing log-safety
  changelog/@unreleased/pr-665.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
Labels: autorelease, merge when ready

#667 Declare PathTemplate is Immutable
  dialogue-target/src/main/java/com/palantir/dialogue/PathTemplate.java
Labels: autorelease, merge when ready, no changelog

#668 Apache HttpClient is configured not to normalize URIs
  changelog/@unreleased/pr-668.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
Labels: autorelease, merge when ready

#672 Implement PreferLowestUtilization without a cache
  dialogue-core/src/main/java/com/palantir/dialogue/core/PreferLowestUtilization.java
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[UNLIMITED_ROUND_ROBIN].png
Labels: merge when ready

#674 [test-only] make 'fast_503s_then_revert' simulation fail faster
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/fast_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/txt/fast_500s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/fast_500s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_500s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/fast_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_503s_then_revert[UNLIMITED_ROUND_ROBIN].txt
Labels: merge when ready, no changelog

#676 Exponential Decaying reservoir for the Balanced algorithm
  dialogue-core/src/main/java/com/palantir/dialogue/core/Balanced.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/CoarseExponentialDecay.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/BalancedTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/CoarseExponentialDecayTest.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_503s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_big_spike[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].txt
Labels: merge when ready

#677 Changelog for new Balanced impl
  changelog/@unreleased/balanced.v2.yml
Labels: autorelease, merge when ready

#679 Update channel names to suggest they're node selection strategies
  README.md
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/CoarseExponentialDecayReservoir.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/CoarseExponentialDecayReservoirTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannelTest.java
Labels: merge when ready, no changelog

#681 Logs & metrics for the Balanced node selection strategy
  changelog/@unreleased/metrics-for-balanced.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueInternalWeakReducingGauge.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueInternalWeakReducingGaugeTest.java
Labels: autorelease, merge when ready

#594 Promote smile encoding to be preferred over json response encoding
  changelog/@unreleased/pr-594.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultConjureRuntime.java
Labels: autorelease, merge when ready

#684 Balanced channels use a multiplier on input for less jagged decay
  changelog/@unreleased/pr-684.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  simulation/src/test/resources/fast_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/txt/fast_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_503s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].txt
Labels: autorelease, merge when ready

#687 fix changelog
  changelog/@unreleased/pr-594.v2.yml
Labels: no changelog

#689 PinUntilError stable hostindex metrics
  changelog/@unreleased/pr-689.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannelTest.java
Labels: autorelease, merge when ready

#690 [pure refactor] simplify DialogueChannel a little
  .palantir/revapi.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ActiveRequestInstrumentationChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Config.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DeprecationWarningChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/InstrumentedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategies.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/SupplierChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/VersionedTaggedMetricRegistry.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ZeroUriNodeSelectionChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ActiveRequestInstrumentationChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/InstrumentedChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
  simulation/src/main/java/com/palantir/dialogue/core/Benchmark.java
Labels: merge when ready, no changelog

#692 [Pure-refactor] Factor out node selection strategy logic
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategies.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#696 Leak detection is disabled by default
  changelog/@unreleased/pr-696.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ResponseLeakDetector.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ResponseLeakDetectorTest.java
Labels: autorelease, merge when ready

#695 [pure refactor] Two more convenience methods
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
Labels: merge when ready, no changelog

#697 README for server side node selection
  README.md
  changelog/@unreleased/pr-688.v2.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/NodeSelectionStrategyChannelTest.java
Labels: merge when ready, no changelog
