Repository palantir/dialogue, pull requests merged in 2020-05, with the labels that each got.

#688 Client respect `Node-Selection-Strategy` response header
  README.md
  changelog/@unreleased/pr-688.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueNodeSelectionStrategy.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChooser.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueNodeSelectionStrategyTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/NodeSelectionStrategyChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannelTest.java
Labels: autorelease, merge when ready

#705 Helpful toString implementations for debugging
  .palantir/revapi.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ActiveRequestInstrumentationChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ChannelToLimitedChannelAdapter.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ContentDecodingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DeprecationWarningChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueTracedRequestChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TracedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/UserAgentChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelsTest.java
Labels: merge when ready, no changelog

#706 Render metrics
  dialogue-core/build.gradle
  dialogue-core/metrics.md
Labels: merge when ready, no changelog

#708 SafeLoggingHttpClientConnectionManager records where the pool is closed
  changelog/@unreleased/pr-708.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/SafeLoggingHttpClientConnectionManager.java
Labels: autorelease, merge when ready

#709 Apache channels allow requests after close has been called
  changelog/@unreleased/pr-709.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/SafeLoggingHttpClientConnectionManager.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
Labels: autorelease, merge when ready

#694 New fluent DialogueClients classes as replacement for WC's DialogueClientFactory
  .gitattributes
  README.md
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-clients/build.gradle
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/AugmentClientConfig.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelCache.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelNames.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DialogueClients.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/Reflection.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/ChannelCacheTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/ChannelNamesTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsIntegrationTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Config.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RefreshingChannelFactory.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/TestConfigurations.java
  settings.gradle
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#715 ApacheHttpClientChannels create/close metrics
  changelog/@unreleased/pr-715.v2.yml
  dialogue-apache-hc4-client/build.gradle
  dialogue-apache-hc4-client/metrics.md
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-clients/build.gradle
  dialogue-clients/metrics.md
  dialogue-core/build.gradle
Labels: merge when ready

#714 Fix a thread leak from unclosed httpclients
  changelog/@unreleased/pr-714.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/IntegrationTest.java
Labels: autorelease, merge when ready

#710 [test-only] simulation for blue/green upgrades when the new node returns 400s
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/fast_400s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_400s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_400s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/txt/fast_400s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/fast_400s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_400s_then_revert[UNLIMITED_ROUND_ROBIN].txt
Labels: merge when ready, no changelog

#716 New `dialogue.client.create` metric when DialogueChannel is created
  changelog/@unreleased/pr-716.v2.yml
  dialogue-apache-hc4-client/build.gradle
  dialogue-apache-hc4-client/metrics.md
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-clients/metrics.md
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
Labels: autorelease, merge when ready

#717 Dialogue can record info to a HostEventsSink
  changelog/@unreleased/pr-717.v2.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/AugmentClientConfig.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/HostMetricsChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/HostMetricsChannelTest.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#711 Balanced now considers 4xx responses when ranking channels
  .palantir/revapi.yml
  changelog/@unreleased/pr711.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/CoarseExponentialDecayReservoir.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Responses.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/CoarseExponentialDecayReservoirTest.java
  simulation/src/test/resources/fast_400s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_400s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/txt/fast_400s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_400s_then_revert[UNLIMITED_ROUND_ROBIN].txt
Labels: autorelease, merge when ready

#726 Dialogue should not propagate retry-other
  changelog/@unreleased/pr-726.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoder.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoderTest.java
Labels: autorelease, merge when ready

#727 Idle connections are checked and timed out more frequently
  changelog/@unreleased/pr-727.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
Labels: autorelease, merge when ready

#729 fix #728 308 retry-other responses don't use exponential backoff
  changelog/@unreleased/pr-729.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/Responses.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
Labels: autorelease, merge when ready

#734 Eliminate a lambda in TraceEnrichingChannel
  dialogue-core/src/main/java/com/palantir/dialogue/core/TraceEnrichingChannel.java
Labels: merge when ready, no changelog

#732 [test-only] Speed up simulations
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  simulation/src/main/java/com/palantir/dialogue/core/Benchmark.java
  simulation/src/main/java/com/palantir/dialogue/core/Simulation.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationMetricsReporter.java
  simulation/src/main/java/com/palantir/dialogue/core/TestCaffeineTicker.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/all_nodes_500[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/fast_400s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_400s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_400s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/fast_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/black_hole[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/drastic_slowdown[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_400s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_400s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_503s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[UNLIMITED_ROUND_ROBIN].png
Labels: merge when ready, no changelog

#737 Minor logging tweaks
  changelog/@unreleased/pr-737.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
Labels: merge when ready

#738 Concurrency limiters have more backpressure against increases
  changelog/@unreleased/pr-738.v2.yml
  dialogue-client-verifier/src/test/java/com/palantir/verification/IntegrationTest.java
  dialogue-client-verifier/src/test/resources/log4j2-test.xml
  dialogue-core/src/main/java/com/palantir/dialogue/core/CautiousIncreaseAggressiveDecreaseConcurrencyLimiter.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/CautiousIncreaseAggressiveDecreaseConcurrencyLimiterTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
Labels: autorelease, merge when ready

#739 [test-only] Run all simulations in parallel
  simulation/build.gradle
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/junit-platform.properties
  versions.lock
Labels: merge when ready, no changelog

#740 IdleConnectionEvictor is started
  changelog/@unreleased/pr-740.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
Labels: autorelease, merge when ready, no changelog

#741 Declare precise deps with api/implementation
  build.gradle
  changelog/@unreleased/pr-741.v2.yml
  dialogue-apache-hc4-client/build.gradle
  dialogue-blocking-channels/build.gradle
  dialogue-client-verifier/build.gradle
  dialogue-clients/build.gradle
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/ContentDecodingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueFutures.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-example/build.gradle
  dialogue-httpurlconnection-client/build.gradle
  dialogue-java-client/build.gradle
  dialogue-okhttp-client/build.gradle
  dialogue-serde/build.gradle
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/JacksonEmptyContainerLoader.java
  dialogue-target/build.gradle
  dialogue-test-common/build.gradle
  simulation/build.gradle
  versions.lock
Labels: merge when ready

#742 DialogueNodeSelectionStrategy is compatible with old guava
  changelog/@unreleased/pr-742.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueNodeSelectionStrategy.java
Labels: autorelease, merge when ready

#744 ApacheHttpClientBlockingChannel uses the client via CloseableClient
  changelog/@unreleased/pr-744.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
Labels: autorelease, merge when ready

#749 [test-only] Fix pin until error reshuffling in simulations
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannelTest.java
  simulation/src/test/resources/report.md
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/txt/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
Labels: merge when ready, no changelog

#752 Eliminate stream, findFirst from BalancedNodeSelectionStrategyChannel
  changelog/@unreleased/pr-752.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
Labels: merge when ready

#751 Eliminate an Optional#map from a PinUntilErrorChannel hot codepath
  changelog/@unreleased/pr-751.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannel.java
Labels: autorelease, merge when ready

#753 [test-only] speed up simulations
  dialogue-test-common/src/main/java/com/palantir/dialogue/TestResponse.java
  simulation/build.gradle
  simulation/src/main/java/com/palantir/dialogue/core/Benchmark.java
  simulation/src/main/java/com/palantir/dialogue/core/MetricNames.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationMetricsReporter.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationServer.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationUtils.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
Labels: merge when ready, no changelog

#754 NSSChannel no longer uses Optional#map with a method reference
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
Labels: merge when ready, no changelog

#750 [test-only] Simulation case for server-side rate limits
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/report.md
  simulation/src/test/resources/server_side_rate_limits[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/server_side_rate_limits[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/server_side_rate_limits[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/txt/server_side_rate_limits[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/server_side_rate_limits[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/server_side_rate_limits[UNLIMITED_ROUND_ROBIN].txt
Labels: merge when ready, no changelog

#748 Dialogue clients do not fail when a Content-Length header is provided
  changelog/@unreleased/pr-748.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueNodeSelectionStrategy.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
Labels: autorelease, merge when ready

#765 Fix the DialogueChannel test name
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelTest.java
Labels: merge when ready, no changelog

#768 [test-only] JMH microbenchmarks
  .gitignore
  dialogue-jmh/build.gradle
  dialogue-jmh/src/main/java/com/palantir/dialogue/core/EndToEndBenchmark.java
  dialogue-jmh/src/main/java/com/palantir/dialogue/core/NodeSelectionBenchmark.java
  dialogue-jmh/src/main/resources/log4j2.xml
  settings.gradle
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#771 QueuedChannel logging uses correct slf4j substitutions
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
Labels: merge when ready, no changelog

#774 Fix publish
  .circleci/config.yml
  dialogue-core/src/test/resources/tracing/DialogueChannelTest/traces_on_retries.log
  dialogue-core/src/test/resources/tracing/DialogueChannelTest/traces_on_success.log
Labels: merge when ready, no changelog

#775 [pure refactor] Cleanup hand-rolled code
  dialogue-client-verifier/src/test/java/com/palantir/verification/IntegrationTest.java
  dialogue-example/dialogue-example-dialogue/src/main/java/com/palantir/dialogue/example/SampleServiceAsync2.java
  dialogue-example/dialogue-example-dialogue/src/main/java/com/palantir/dialogue/example/SampleServiceBlocking2.java
  dialogue-jmh/src/main/java/com/palantir/dialogue/core/EndToEndBenchmark.java
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#759 Blocking clients wrap checked failures with DialogueException
  changelog/@unreleased/pr-759.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DialogueException.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsBlockingTest.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractSampleServiceClientTest.java
Labels: autorelease, merge when ready

#777 Optimize tracing channels
  changelog/@unreleased/pr-777.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueTracedRequestChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TraceEnrichingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TracedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/TraceEnrichingChannelTest.java
  dialogue-jmh/src/main/java/com/palantir/dialogue/core/EndToEndBenchmark.java
Labels: autorelease, merge when ready

#776 Reduce mutability by deleting DialogueChannel#updateUris
  .palantir/revapi.yml
  changelog/@unreleased/pr-776.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ActiveRequestInstrumentationChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/HostMetricsChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/InstrumentedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TracedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/HostMetricsChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/NodeSelectionStrategyChannelTest.java
  dialogue-jmh/src/main/java/com/palantir/dialogue/core/NodeSelectionBenchmark.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_400s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/fast_503s_then_revert[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/server_side_rate_limits[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/server_side_rate_limits[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/server_side_rate_limits[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/fast_400s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/fast_503s_then_revert[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/fast_503s_then_revert[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/server_side_rate_limits[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/server_side_rate_limits[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/server_side_rate_limits[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/simplest_possible_case[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[UNLIMITED_ROUND_ROBIN].txt
Labels: merge when ready

#780 `client.response` timer now measures user-perceived time
  changelog/@unreleased/pr-780.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/InstrumentedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TimingEndpointChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/InstrumentedChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/TimingEndpointChannelTest.java
  simulation/src/main/java/com/palantir/dialogue/core/Benchmark.java
Labels: autorelease, merge when ready

#781 Tracing around dialogue encodings
  changelog/@unreleased/pr-781.v2.yml
  dialogue-serde/build.gradle
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/LazilyInitializedEncoding.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/TracedEncoding.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/TracedEncodingTest.java
Labels: autorelease, merge when ready

#783 ChannelCache doesn't log existing instances
  changelog/@unreleased/pr-783.v2.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelCache.java
Labels: autorelease, merge when ready

#784 Fallback default impl for Clients.bind
  dialogue-target/src/main/java/com/palantir/dialogue/Clients.java
Labels: autorelease, merge when ready, no changelog

#786 Undo deprecation of Clients.call
  changelog/@unreleased/pr-786.v2.yml
  dialogue-target/src/main/java/com/palantir/dialogue/Clients.java
Labels: autorelease, merge when ready

#785 Delete dialogue.client.request.active to save $ and CPU
  changelog/@unreleased/pr-785.v2.yml
  dialogue-clients/metrics.md
  dialogue-core/src/main/java/com/palantir/dialogue/core/ActiveRequestInstrumentationChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/ActiveRequestInstrumentationChannelTest.java
Labels: autorelease, merge when ready

#791 Optimize Request.builder().from()
  changelog/@unreleased/pr-791.v2.yml
  dialogue-jmh/src/main/java/com/palantir/dialogue/core/RequestBuilderBenchmark.java
  dialogue-target/src/main/java/com/palantir/dialogue/Request.java
  dialogue-target/src/test/java/com/palantir/dialogue/RequestTest.java
Labels: autorelease, merge when ready

#793 Minor simulation speedups
  simulation/src/main/java/com/palantir/dialogue/core/Benchmark.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
Labels: merge when ready, no changelog

#795 Optimize Request.Builder size and allocations
  changelog/@unreleased/pr-795.v2.yml
  dialogue-target/src/main/java/com/palantir/dialogue/Request.java
Labels: autorelease, merge when ready

#802 Support http OPTIONS
  changelog/@unreleased/pr-802.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientBlockingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-httpurlconnection-client/src/main/java/com/palantir/dialogue/httpurlconnection/HttpUrlConnectionBlockingChannel.java
  dialogue-java-client/src/main/java/com/palantir/dialogue/HttpChannel.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannel.java
  dialogue-target/src/main/java/com/palantir/dialogue/HttpMethod.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
Labels: merge when ready
