Repository palantir/dialogue, pull requests merged in 2020-07, with the labels that each got.

#882 [stacked] Comments and debug log lines
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedScoreTracker.java
Labels: merge when ready, no changelog

#873 Resolve low success rate of `short_outage_on_one_node` with limiter+balanced
  README.md
  changelog/@unreleased/pr-873.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedScoreTracker.java
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/server_side_rate_limits[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/short_outage_on_one_node[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/server_side_rate_limits[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/short_outage_on_one_node[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
Labels: autorelease, merge when ready

#884 Remove dialogue-apache-hc4-client in favor of hc5
  changelog/@unreleased/pr-884.v2.yml
  dialogue-apache-hc4-client/build.gradle
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ResponseLeakDetector.java
  dialogue-apache-hc4-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheProxyConfigTest.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheProxyConfigTlsTest.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ResponseLeakDetectorTest.java
  dialogue-apache-hc4-client/src/test/resources/tracing/ApacheHttpClientChannelsTest/requestAreTraced.log
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-client-verifier/build.gradle
  dialogue-client-verifier/src/test/java/com/palantir/verification/AutoDeserializeTest.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/IntegrationTest.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/SingleParamServicesTest.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/VerificationClients.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/VerificationServerRule.java
  dialogue-jmh/build.gradle
  dialogue-jmh/src/main/java/com/palantir/dialogue/core/EndToEndBenchmark.java
  settings.gradle
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#888 Update DialogueClientsTest uris to avoid resolving internally
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsTest.java
Labels: merge when ready, no changelog

#889 Instrument the ScheduledIdleConnectionEvictor scheduler
  changelog/@unreleased/pr-889.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ScheduledIdleConnectionEvictor.java
Labels: merge when ready

#887 Dialogue validates connections after four seconds of inactivity
  changelog/@unreleased/pr-887.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
Labels: autorelease, merge when ready

#891 Dialogue POST requests with no body set `Content-Length: 0`
  changelog/@unreleased/pr-891.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientBlockingChannel.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
Labels: autorelease, merge when ready

#892 Dialogue PUT requests with no body set `Content-Length: 0`
  changelog/@unreleased/pr-892.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientBlockingChannel.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
Labels: autorelease, merge when ready

#895 Better concurrency limiter metrics for StickyEndpointChannels
  changelog/@unreleased/pr-895.v2.yml
  dialogue-clients/build.gradle
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelCache.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Config.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
Labels: autorelease, merge when ready

#897 ConcurrencyLimiter tries harder to stay under the (floating point) limit
  changelog/@unreleased/pr-897.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/CautiousIncreaseAggressiveDecreaseConcurrencyLimiter.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/server_side_rate_limits[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/server_side_rate_limits[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/short_outage_on_one_node[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/short_outage_on_one_node[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/server_side_rate_limits[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/server_side_rate_limits[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/short_outage_on_one_node[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/short_outage_on_one_node[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
Labels: autorelease, merge when ready

#901 Fix unexpected socket timeouts when configured as unlimited
  changelog/@unreleased/pr-901.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsIntegrationTest.java
Labels: autorelease, merge when ready

#908 Fix massive synchronization and gc cost of jaxrs clients
  changelog/@unreleased/pr-908.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
Labels: autorelease, merge when ready

#912 Fix UnsupportedOperationException with old dialouge bindings
  changelog/@unreleased/pr-912.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/StickyEndpointChannels.java
Labels: autorelease, merge when ready

#913 Clients respect the server Keep-Alive timeout when present
  changelog/@unreleased/pr-913.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ScheduledIdleConnectionEvictor.java
Labels: autorelease, merge when ready

#915 The validateAfterInactivity duration may be modified via a sysprop
  changelog/@unreleased/pr-915.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
Labels: autorelease, merge when ready

#918 PDS-127702: Dialogue Apahce Httpclient connections produce tracing spans
  changelog/@unreleased/pr-918.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/TracedManagedHttpClientConnection.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/TracedManagedHttpConnectionFactory.java
  dialogue-apache-hc5-client/src/test/resources/tracing/ApacheHttpClientChannelsTest/requestAreTraced.log
Labels: autorelease, merge when ready

#919 Trace LeaseRequest
  changelog/@unreleased/pr-919.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/TracedPoolingHttpClientConnectionManager.java
  dialogue-apache-hc5-client/src/test/resources/tracing/ApacheHttpClientChannelsTest/requestAreTraced.log
Labels: autorelease, merge when ready

#917 Disable the response-out-of-order check
  changelog/@unreleased/pr-917.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/DialogueConnectionFactory.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/DialogueManagedHttpClientConnection.java
Labels: autorelease, merge when ready

#920 Connect timeouts are retried
  changelog/@unreleased/pr-920.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientBlockingChannel.java
Labels: autorelease, merge when ready

#925 QueuedChannel logs cancellation exceptions at debug
  changelog/@unreleased/pr-925.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
Labels: merge when ready

#928 Empty HttpEntity which doesn't attempt a write or flush
  changelog/@unreleased/pr-928.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/EmptyHttpEntity.java
Labels: merge when ready

#924 Fix response leaks on Future.cancel
  changelog/@unreleased/pr-924.v2.yml
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ContentDecodingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DeprecationWarningChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueFutures.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/HostMetricsChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/StickyEndpointChannels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TimingEndpointChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TraceEnrichingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/StickyEndpointChannelsTest.java
  dialogue-futures/build.gradle
  dialogue-futures/src/main/java/com/palantir/dialogue/futures/DialogueDirectAsyncCatchingFuture.java
  dialogue-futures/src/main/java/com/palantir/dialogue/futures/DialogueDirectAsyncTransformationFuture.java
  dialogue-futures/src/main/java/com/palantir/dialogue/futures/DialogueDirectTransformationFuture.java
  dialogue-futures/src/main/java/com/palantir/dialogue/futures/DialogueFutures.java
  dialogue-futures/src/test/java/com/palantir/dialogue/futures/DialogueFuturesTest.java
  dialogue-serde/build.gradle
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  settings.gradle
  simulation/build.gradle
  simulation/src/main/java/com/palantir/dialogue/core/SimulationServer.java
Labels: autorelease, merge when ready

#930 Handshake time is no longer bounded by the connect timeout
  changelog/@unreleased/pr-930.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/SafeConnectTimeoutException.java
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ApacheHandshakeTimeoutTest.java
Labels: autorelease, merge when ready

#933 Dialogue explicitly sets enabled TLS protocols
  changelog/@unreleased/pr-933.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
Labels: autorelease, merge when ready

#935 Report metrics describing the time spent creating a new connection
  changelog/@unreleased/pr-935.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedPoolingHttpClientConnectionManager.java
  dialogue-apache-hc5-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-clients/metrics.md
Labels: autorelease, merge when ready
