Repository palantir/dialogue, pull requests merged in 2020-06, with the labels that each got.

#794 Balanced channel measures RTT, hoping to stay within AZ (and save $)
  changelog/@unreleased/pr-794.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueNodeSelectionStrategy.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RttSampler.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/UserAgentEndpointChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueNodeSelectionStrategyTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RttSamplerTest.java
  dialogue-jmh/src/main/java/com/palantir/dialogue/core/NodeSelectionBenchmark.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationServer.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
Labels: autorelease, merge when ready

#806 Fix BALANCED_RTT (and add simulations)
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RttSampler.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationServer.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
  simulation/src/test/resources/cross_az[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/cross_az[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/cross_az[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/log4j2-test.xml
  simulation/src/test/resources/report.md
  simulation/src/test/resources/txt/cross_az[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/cross_az[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/cross_az[UNLIMITED_ROUND_ROBIN].txt
Labels: merge when ready, no changelog

#809 Try to avoid embedding 0.0.0
  changelog/@unreleased/pr-809.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/UserAgentEndpointChannel.java
Labels: autorelease, merge when ready

#812 Improve deprecation slf4j logging
  changelog/@unreleased/pr-812.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DeprecationWarningChannel.java
Labels: autorelease, merge when ready

#814 BALANCED_RTT uses soft validation on rttSpectrum values
  changelog/@unreleased/pr-814.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/RttSampler.java
Labels: autorelease, merge when ready

#818 DialogueClients takes advantage of the EndpointChannel bind optimization
  changelog/@unreleased/pr-818.v2.yml
  dialogue-clients/build.gradle
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/ReloadingClientFactoryTest.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
Labels: autorelease, merge when ready

#819 parse header BALANCED_RTT2
  changelog/@unreleased/pr-819.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueNodeSelectionStrategy.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueNodeSelectionStrategyTest.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
Labels: autorelease, merge when ready

#823 Fix the Encodings.AbstractJacksonEncoding serializer error message
  changelog/@unreleased/pr-823.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/Encodings.java
Labels: merge when ready

#826 [stacked] Add tracing to the HC5 connection manager
  dialogue-apache-hc5-client/build.gradle
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/TracedPoolingHttpClientConnectionManager.java
  dialogue-apache-hc5-client/src/test/resources/tracing/ApacheHttpClientChannelsTest/requestAreTraced.log
Labels: merge when ready

#827 Trace DNS lookups
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedDnsResolver.java
  dialogue-apache-hc5-client/src/test/resources/tracing/ApacheHttpClientChannelsTest/requestAreTraced.log
Labels: merge when ready

#828 Don't impose c-j-r 6.0
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#833 Reduce IdleConnectionEvictor metrics fanout
  changelog/@unreleased/pr-833.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
Labels: merge when ready

#839 Drop the log level of RttSampler bounds checking
  changelog/@unreleased/pr-839.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/RttSampler.java
Labels: merge when ready

#811 Dialogue uses Apache HttpClient 5
  changelog/1.60.0-rc1/pr-811.v2.yml
  dialogue-apache-hc5-client/build.gradle
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedDnsResolver.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ResponseLeakDetector.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/TracedPoolingHttpClientConnectionManager.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/TracingExecChainHandler.java
  dialogue-apache-hc5-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ApacheHttpClientChannelsTest.java
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ApacheProxyConfigTest.java
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ResponseLeakDetectorTest.java
  dialogue-apache-hc5-client/src/test/resources/tracing/ApacheHttpClientChannelsTest/requestAreTraced.log
  dialogue-clients/build.gradle
  dialogue-clients/metrics.md
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelCache.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/ChannelCacheTest.java
  settings.gradle
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#840 Disable hc5 revapi until we've published a release
  changelog/@unreleased/pr-840.v2.yml
  dialogue-apache-hc5-client/build.gradle
Labels: autorelease, merge when ready

#841 Fix unbounded socket timeouts resulting in high CPU load
  changelog/@unreleased/pr-841.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
Labels: autorelease, merge when ready

#844 Prevent clients from being collected while streams are read
  changelog/@unreleased/pr-844.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientBlockingChannel.java
Labels: autorelease, merge when ready

#845 Remove cruft from dialogue-client-verifier logging config
  dialogue-client-verifier/src/test/resources/log4j2-test.xml
Labels: merge when ready, no changelog

#854 Dialogue url encoding escapes uri sub-delimiter characters
  changelog/@unreleased/pr-854.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BaseUrl.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/UrlBuilderTest.java
Labels: autorelease, merge when ready

#858 RetryingChannel scheduler uses daemon threads
  changelog/@unreleased/pr-858.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
Labels: autorelease, merge when ready

#859 Reduce peak thread count using a scheduled executor for eviction
  changelog/@unreleased/pr-859.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ScheduledIdleConnectionEvictor.java
Labels: autorelease, merge when ready

#860 use metric-schema for our lazy gauges
  build.gradle
  changelog/@unreleased/pr-860.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
Labels: autorelease, merge when ready

#861 Work around http proxy timeouts caused by HTTPCLIENT-1478
  changelog/@unreleased/pr-861.v2.yml
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheProxyConfigTlsTest.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ApacheProxyConfigTlsTest.java
  dialogue-okhttp-client/src/test/java/com/palantir/dialogue/OkHttpProxyConfigTlsTest.java
  dialogue-test-common/build.gradle
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractProxyConfigTlsTest.java
Labels: autorelease, merge when ready

#864 eliminate false positive warning logs
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
Labels: merge when ready, no changelog

#867 [prereq] Pull out Balanced logic to a BalancedScoreTracker
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedScoreTracker.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueNodeSelectionStrategy.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RttSampler.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueNodeSelectionStrategyTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RttSamplerTest.java
  dialogue-jmh/src/main/java/com/palantir/dialogue/core/NodeSelectionBenchmark.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/cross_az[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/txt/cross_az[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
Labels: merge when ready, no changelog

#853 StickyChannelFactory
  .palantir/revapi.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelCache.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelNames.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DialogueClients.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsTest.java
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/StickyEndpointChannels.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/StickyEndpointChannelsTest.java
Labels: autorelease, merge when ready, no changelog

#872 [simulation only] Simulate a short outage on one of two nodes
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/report.md
  simulation/src/test/resources/short_outage_on_one_node[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/short_outage_on_one_node[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/short_outage_on_one_node[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/txt/short_outage_on_one_node[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/short_outage_on_one_node[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/short_outage_on_one_node[UNLIMITED_ROUND_ROBIN].txt
Labels: merge when ready, no changelog

#870 Allow dialogue-hc5 to support TLSv1.3 when ciphers are available
  changelog/@unreleased/pr-870.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
Labels: autorelease, merge when ready

#879 DialogueException is public, may be caught and handled by consumers
  changelog/@unreleased/pr-879.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsBlockingTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/DialogueException.java
Labels: autorelease, merge when ready
