Repository palantir/dialogue, pull requests merged in 2020-02, with the labels that each got.

#290 [improvement] dialogue-core targets jdk8
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/InstrumentedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
Labels: merge when ready

#295 Backstop against exceptions thrown in Channel impls
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NeverThrowChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ChannelsTest.java
Labels: merge when ready

#310 Match CJR okhttp version
  versions.lock
  versions.props
Labels: merge when ready

#303 [improvement] QueuedChannel avoids queue contention in the fast path
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
Labels: merge when ready

#330 Disable revapi as we iterate on the API
  build.gradle
  dialogue-core/build.gradle
  dialogue-java-client/build.gradle
  dialogue-okhttp-client/build.gradle
  dialogue-serde/build.gradle
  dialogue-target/build.gradle
Labels: merge when ready, no changelog

#337 [break][improvement] RequestBody.length uses OptionalLong
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-target/src/main/java/com/palantir/dialogue/EmptyBody.java
  dialogue-target/src/main/java/com/palantir/dialogue/RequestBody.java
  dialogue-target/src/test/java/com/palantir/dialogue/EmptyBodyTest.java
Labels: merge when ready

#338 Use default port if one is not provided
  build.gradle
  dialogue-java-client/src/main/java/com/palantir/dialogue/HttpChannel.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannel.java
  dialogue-target/src/main/java/com/palantir/dialogue/UrlBuilder.java
  dialogue-target/src/test/java/com/palantir/dialogue/PathTemplateTest.java
  dialogue-target/src/test/java/com/palantir/dialogue/UrlBuilderTest.java
Labels: autorelease, merge when ready

#341 improve automation
  .changelog.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: merge when ready, no changelog

#331 fix #326: Requests write to output streams, they don't create inputstreams
  changelog/@unreleased/pr-331.v2.yml
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-java-client/src/main/java/com/palantir/dialogue/HttpChannel.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannel.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-target/src/main/java/com/palantir/dialogue/EmptyBody.java
  dialogue-target/src/main/java/com/palantir/dialogue/RequestBody.java
  dialogue-target/src/test/java/com/palantir/dialogue/EmptyBodyTest.java
Labels: merge when ready

#342 convert client metrics to metric schema
  changelog/@unreleased/pr-342.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DeprecationWarningChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/InstrumentedChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/InstrumentedChannelTest.java
Labels: merge when ready

#345 Delete unused classes from dialogue-target
  changelog/@unreleased/pr-345.v2.yml
  dialogue-target/src/main/java/com/palantir/dialogue/Call.java
  dialogue-target/src/main/java/com/palantir/dialogue/Calls.java
  dialogue-target/src/main/java/com/palantir/dialogue/Header.java
  dialogue-target/src/main/java/com/palantir/dialogue/Observer.java
  dialogue-target/src/test/java/com/palantir/dialogue/CallsTest.java
Labels: merge when ready

#344 Fix dialogue channel tracing
  changelog/@unreleased/pr-344.v2.yml
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-java-client/src/test/java/com/palantir/dialogue/HttpChannelTest.java
  dialogue-okhttp-client/build.gradle
  dialogue-okhttp-client/src/test/java/com/palantir/dialogue/OkHttpChannelTest.java
Labels: merge when ready

#288 [fix][break] Dialogue `Request` header names are case insensitive
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-client-test-lib/src/main/resources/mockito-extensions/org.mockito.plugins.MockMaker
  dialogue-core/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  dialogue-java-client/src/main/java/com/palantir/dialogue/HttpChannel.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannel.java
  dialogue-target/build.gradle
  dialogue-target/src/main/java/com/palantir/dialogue/Request.java
  dialogue-target/src/test/java/com/palantir/dialogue/RequestTest.java
  versions.lock
  versions.props
Labels: merge when ready

#289 [improvement] Implement a generalized ContentDecodingChannel for gzip support
  changelog/@unreleased/pr-289.v2.yml
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ContentDecodingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ContentDecodingChannelTest.java
  dialogue-java-client/src/main/java/com/palantir/dialogue/HttpChannel.java
Labels: merge when ready

#352 [pure refactor] RefreshingChannelFactory exposes generic version
  dialogue-core/src/main/java/com/palantir/dialogue/core/RefreshingChannelFactory.java
Labels: merge when ready, no changelog

#348 [test-only] Simulate dialogue clients against a DeterministicScheduler
  .gitignore
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
  settings.gradle
  simulation/build.gradle
  simulation/src/main/java/com/palantir/dialogue/core/Benchmark.java
  simulation/src/main/java/com/palantir/dialogue/core/CodahaleClock.java
  simulation/src/main/java/com/palantir/dialogue/core/EventMarkers.java
  simulation/src/main/java/com/palantir/dialogue/core/HistogramChannel.java
  simulation/src/main/java/com/palantir/dialogue/core/Simulation.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationMetrics.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationServer.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationUtils.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/all_nodes_500[ROUND_ROBIN].png
  simulation/src/test/resources/all_nodes_500[ROUND_ROBIN].txt
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/black_hole[ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[ROUND_ROBIN].txt
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/drastic_slowdown[ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[ROUND_ROBIN].txt
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/fast_500s_then_revert[ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[ROUND_ROBIN].txt
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/live_reloading[ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[ROUND_ROBIN].txt
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/one_endpoint_dies_on_each_server[ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[ROUND_ROBIN].txt
  simulation/src/test/resources/report.txt
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/simplest_possible_case[ROUND_ROBIN].png
  simulation/src/test/resources/simplest_possible_case[ROUND_ROBIN].txt
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/slow_503s_then_revert[ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[ROUND_ROBIN].txt
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/slowdown_and_error_thresholds[ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[ROUND_ROBIN].txt
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#356 [test-only] Markdown comparisons for graphs
  .gitattributes
  simulation/src/main/java/com/palantir/dialogue/core/Simulation.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/all_nodes_500[ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/black_hole[ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/drastic_slowdown[ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/fast_500s_then_revert[ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/live_reloading[ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/report.txt
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/simplest_possible_case[ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/slow_503s_then_revert[ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/slowdown_and_error_thresholds[ROUND_ROBIN].png
Labels: merge when ready, no changelog

#354 JavaChannels respects the client configuration `enableHttp2` flag
  changelog/@unreleased/pr-354.v2.yml
  dialogue-java-client/src/main/java/com/palantir/dialogue/JavaChannels.java
Labels: merge when ready

#350 RetryingChannel retries 429/503s
  changelog/@unreleased/pr-350.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/slow_503s_then_revert[ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[ROUND_ROBIN].txt
Labels: merge when ready

#355 Implement an OkHttpChannels factory class
  changelog/@unreleased/pr-355.v2.yml
  dialogue-okhttp-client/build.gradle
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannels.java
  dialogue-okhttp-client/src/test/java/com/palantir/dialogue/OkHttpChannelTest.java
Labels: merge when ready

#359 Simplify InstrumentedChannel
  changelog/@unreleased/pr-359.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/InstrumentedChannel.java
Labels: merge when ready

#360 fix #353: Response is closeable
  changelog/@unreleased/pr-360.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ContentDecodingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ContentDecodingChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
  dialogue-java-client/src/main/java/com/palantir/dialogue/HttpChannel.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpResponse.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDeTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultErrorDecoderTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/Response.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationUtils.java
Labels: merge when ready

#365 Faster gradle
  build.gradle
  gradle.properties
  settings.gradle
Labels: merge when ready, no changelog

#366 Support disabling client QoS
  changelog/@unreleased/pr-366.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheApacheHttpClientChannelsTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/UnlimitedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ChannelsTest.java
  dialogue-httpurlconnection-client/src/main/java/com/palantir/dialogue/httpurlconnection/HttpUrlConnectionChannels.java
  dialogue-httpurlconnection-client/src/test/java/com/palantir/dialogue/httpurlconnection/HttpUrlConnectionChannelsTest.java
  dialogue-java-client/src/main/java/com/palantir/dialogue/JavaChannels.java
  dialogue-java-client/src/test/java/com/palantir/dialogue/JavaChannelsTest.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannels.java
  dialogue-okhttp-client/src/test/java/com/palantir/dialogue/OkHttpChannelTest.java
Labels: merge when ready

#367 Fix off-by-one in RetryingChannel, use the configured number of retries
  changelog/@unreleased/pr-367.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueFutures.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
Labels: merge when ready

#369 Migrate dialogue-core to junit-jupiter
  dialogue-core/build.gradle
  dialogue-core/src/test/java/com/palantir/dialogue/core/BlacklistingChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ChannelsTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ContentDecodingChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/InstrumentedChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/MemoizingComposingSupplierTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RefreshingChannelFactoryTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RoundRobinChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/UserAgentChannelTest.java
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#364 Make the pin until error strategy available
  changelog/@unreleased/pr-364.v2.yml
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/SafeThreadLocalRandom.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/SafeThreadLocalRandomTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
  simulation/src/test/resources/all_nodes_500[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/all_nodes_500[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/black_hole[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/black_hole[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/drastic_slowdown[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/fast_500s_then_revert[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_500s_then_revert[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/live_reloading[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/one_endpoint_dies_on_each_server[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/report.md
  simulation/src/test/resources/simplest_possible_case[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/simplest_possible_case[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/slow_503s_then_revert[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slow_503s_then_revert[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/slowdown_and_error_thresholds[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[PIN_UNTIL_ERROR].txt
Labels: merge when ready

#349 BlacklistingChannel probation and per-endpoint info
  changelog/@unreleased/pr-349.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BlacklistingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/BlacklistingChannelTest.java
Labels: merge when ready

#374 [test-only] SimulationTest runs with 10 clients each time
  dialogue-core/src/test/java/com/palantir/dialogue/core/SafeThreadLocalRandomTest.java
  simulation/src/main/java/com/palantir/dialogue/core/Benchmark.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationMetricsReporter.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/all_nodes_500[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/all_nodes_500[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/all_nodes_500[ROUND_ROBIN].png
  simulation/src/test/resources/all_nodes_500[ROUND_ROBIN].txt
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/black_hole[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/black_hole[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/black_hole[ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[ROUND_ROBIN].txt
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/drastic_slowdown[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/drastic_slowdown[ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[ROUND_ROBIN].txt
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/fast_500s_then_revert[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/fast_500s_then_revert[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/fast_500s_then_revert[ROUND_ROBIN].png
  simulation/src/test/resources/fast_500s_then_revert[ROUND_ROBIN].txt
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/live_reloading[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/live_reloading[ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[ROUND_ROBIN].txt
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/one_endpoint_dies_on_each_server[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/one_endpoint_dies_on_each_server[ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[ROUND_ROBIN].txt
  simulation/src/test/resources/report.md
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/simplest_possible_case[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/simplest_possible_case[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/simplest_possible_case[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/simplest_possible_case[ROUND_ROBIN].png
  simulation/src/test/resources/simplest_possible_case[ROUND_ROBIN].txt
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/slow_503s_then_revert[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slow_503s_then_revert[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/slow_503s_then_revert[ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[ROUND_ROBIN].txt
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER].txt
  simulation/src/test/resources/slowdown_and_error_thresholds[PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/slowdown_and_error_thresholds[ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[ROUND_ROBIN].txt
Labels: merge when ready, no changelog

#378 Respect ClientConfiguration.serverQos
  changelog/@unreleased/pr-378.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannels.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
Labels: merge when ready

#385 Trace entire reqeuest
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ChannelsTest.java
  dialogue-core/src/test/resources/tracing/ChannelsTest/traces_on_retries.log
  dialogue-core/src/test/resources/tracing/ChannelsTest/traces_on_succes.log
  versions.lock
Labels: merge when ready, no changelog

#383 Apache channel supports proxy credentials
  changelog/@unreleased/pr-383.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheProxyConfigTest.java
  dialogue-client-test-lib/build.gradle
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractProxyConfigTest.java
  dialogue-client-test-lib/src/main/resources/keyStore.jks
  dialogue-client-test-lib/src/main/resources/trustStore.jks
  dialogue-okhttp-client/src/test/java/com/palantir/dialogue/OkHttpProxyConfigTest.java
Labels: merge when ready

#387 fix #301: QueuedChannel futures don't wait forever when delegates throw
  changelog/@unreleased/pr-387.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/NeverThrowLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
Labels: merge when ready

#390 QueuedChannel.scheduleNextTask applies components.span
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/test/resources/tracing/QueuedChannelTest/testQueueTracing.log
Labels: merge when ready

#393 fix #392: QueuedChannel no longer leaks responses on cancel
  changelog/@unreleased/pr-393.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
Labels: merge when ready

#388 client tolerates unexpected body
  changelog/@unreleased/pr-388.v2.yml
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractSampleServiceClientTest.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
Labels: autorelease, merge when ready

#394 fix #391: QueuedChannel correctly propagates cancellation
  changelog/@unreleased/pr-394.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
Labels: merge when ready

#395 fix #386: Limit connections-per-host using a LimitedChannel
  changelog/@unreleased/pr-395.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/FixedLimitedChannelTest.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannels.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
Labels: merge when ready

#396 Clean up channel chain ergonomics
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/LimitedChannelAdapter.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
Labels: merge when ready, no changelog

#399 Fix test name, gzip is an encoding
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
Labels: merge when ready, no changelog

#400 Fix test names
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractSampleServiceClientTest.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
Labels: merge when ready, no changelog

#412 fix #411: RemoteExceptions.getUnchecked cancels futures on interruption
  changelog/@unreleased/pr-412.v2.yml
  dialogue-target/src/main/java/com/palantir/dialogue/RemoteExceptions.java
  dialogue-target/src/test/java/com/palantir/dialogue/RemoteExceptionsTest.java
Labels: merge when ready

#402 Centralize status code checks in a utility class
  changelog/@unreleased/pr-402.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BlacklistingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Responses.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorChannelTest.java
Labels: merge when ready

#409 Record metrics any time a channel limits an outgoing request
  changelog/@unreleased/pr-409.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/FixedLimitedChannelTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
Labels: merge when ready

#414 Responses utility class feedback
  dialogue-core/src/main/java/com/palantir/dialogue/core/Responses.java
Labels: merge when ready, no changelog

#415 ApacheHttpClientChannels no longer complains about `Unsupported ciphersuite`
  changelog/@unreleased/pr-415.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
Labels: autorelease, merge when ready

#410 LimitedChannels operate on channels, ignoring Endpoint and Request
  dialogue-core/src/main/java/com/palantir/dialogue/core/BlacklistingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/LimitedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/BlacklistingChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
Labels: merge when ready, no changelog

#401 Blacklisting channel notifies the queue when it can handle events
  changelog/@unreleased/pr-401.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BlacklistingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/LimitedChannelListener.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/BlacklistingChannelTest.java
  simulation/src/main/java/com/palantir/dialogue/core/Simulation.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
Labels: merge when ready

#419 Simulator scheduler relies on the internal ticker
  simulation/src/main/java/com/palantir/dialogue/core/Benchmark.java
  simulation/src/main/java/com/palantir/dialogue/core/ExternalDeterministicScheduler.java
  simulation/src/main/java/com/palantir/dialogue/core/Simulation.java
  simulation/src/main/java/com/palantir/dialogue/core/SimulationServer.java
  simulation/src/main/java/com/palantir/dialogue/core/TestCaffeineTicker.java
  simulation/src/test/resources/fast_500s_then_revert[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/txt/fast_500s_then_revert[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
Labels: merge when ready, no changelog

#421 Update confusing variable name
  dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java
Labels: merge when ready, no changelog

#346 Utility to safely build URLs
  changelog/@unreleased/pr-346.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientBlockingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/BaseUrl.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PathTemplateTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/UrlBuilderTest.java
  dialogue-httpurlconnection-client/src/main/java/com/palantir/dialogue/httpurlconnection/HttpUrlConnectionBlockingChannel.java
  dialogue-java-client/src/main/java/com/palantir/dialogue/HttpChannel.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannel.java
  dialogue-target/src/main/java/com/palantir/dialogue/UrlBuilder.java
Labels: merge when ready

#418 Simulate low latency with 1% server error rate
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/report.md
  simulation/src/test/resources/txt/uncommon_flakes[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/uncommon_flakes[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/uncommon_flakes[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/uncommon_flakes[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/uncommon_flakes[UNLIMITED_ROUND_ROBIN].png
Labels: merge when ready, no changelog

#408 Simplify AbstractChannelTest implementations
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
  dialogue-apache-hc4-client/src/test/resources/keyStore.jks
  dialogue-apache-hc4-client/src/test/resources/trustStore.jks
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractProxyConfigTest.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/TestConfigurations.java
  dialogue-httpurlconnection-client/src/test/java/com/palantir/dialogue/httpurlconnection/HttpUrlConnectionChannelsTest.java
  dialogue-httpurlconnection-client/src/test/resources/keyStore.jks
  dialogue-httpurlconnection-client/src/test/resources/trustStore.jks
  dialogue-java-client/src/test/java/com/palantir/dialogue/JavaChannelsTest.java
  dialogue-okhttp-client/src/test/java/com/palantir/dialogue/OkHttpChannelTest.java
Labels: merge when ready, no changelog

#423 NullAway
  .gitattributes
  build.gradle
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-client-test-lib/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ContentDecodingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/MemoizingComposingSupplier.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PathTemplateTest.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultErrorDecoderTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/PathTemplate.java
  simulation/build.gradle
  versions.props
Labels: merge when ready, no changelog

#420 Simplify BlacklistingChannel
  dialogue-core/src/main/java/com/palantir/dialogue/core/BlacklistingChannel.java
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
Labels: merge when ready, no changelog

#426 Track png in git-lfs
  .gitattributes
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
Labels: merge when ready, no changelog

#427 Downgrade hc4 to 4.5.10
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#431 Simplify (ClientConfig, UserAgent) signatures to just (ClientConfig)
  changelog/@unreleased/pr-431.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheProxyConfigTest.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractChannelTest.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/AbstractProxyConfigTest.java
  dialogue-client-test-lib/src/main/java/com/palantir/dialogue/TestConfigurations.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ChannelsTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/UserAgentChannelTest.java
  dialogue-httpurlconnection-client/src/main/java/com/palantir/dialogue/httpurlconnection/HttpUrlConnectionChannels.java
  dialogue-httpurlconnection-client/src/test/java/com/palantir/dialogue/httpurlconnection/HttpUrlConnectionChannelsTest.java
  dialogue-java-client/src/main/java/com/palantir/dialogue/JavaChannels.java
  dialogue-java-client/src/test/java/com/palantir/dialogue/JavaChannelsTest.java
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannels.java
  dialogue-okhttp-client/src/test/java/com/palantir/dialogue/OkHttpChannelTest.java
  dialogue-okhttp-client/src/test/java/com/palantir/dialogue/OkHttpProxyConfigTest.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#416 fix #406: QueuedChannel does not leak responses in edge cases
  changelog/@unreleased/pr-416.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
  dialogue-core/src/test/resources/tracing/ChannelsTest/traces_on_retries.log
  dialogue-core/src/test/resources/tracing/ChannelsTest/traces_on_succes.log
  dialogue-core/src/test/resources/tracing/QueuedChannelTest/testQueueTracing.log
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/uncommon_flakes[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/uncommon_flakes[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
Labels: merge when ready

#430 ApacheHttpChannels exposes a Closeable instance
  changelog/@unreleased/pr-430.v2.yml
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
  dialogue-apache-hc4-client/src/test/java/com/palantir/dialogue/hc4/ApacheHttpClientChannelsTest.java
Labels: autorelease, merge when ready

#436 All metrics include dialogueVersion
  changelog/@unreleased/pr-436.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/VersionedTaggedMetricRegistry.java
Labels: autorelease, merge when ready

#441 Tracing spans for RetryingChannel backoff
  changelog/@unreleased/pr-441.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/resources/tracing/ChannelsTest/traces_on_retries.log
Labels: autorelease, merge when ready

#440 Implement missing retry configuration options
  changelog/@unreleased/pr-440.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
Labels: autorelease, merge when ready

#442 Autorelease most PRs
  .github/autolabeler.yml
Labels: merge when ready, no changelog

#437 Metrics for PinUntilErrorChannel
  changelog/@unreleased/pr-437.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorChannelTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
Labels: autorelease, merge when ready

#445 Pin until error strategy attempts to find an active channel
  changelog/@unreleased/pr-445.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorChannelTest.java
  simulation/src/test/resources/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/txt/black_hole[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/drastic_slowdown[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/live_reloading[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slow_503s_then_revert[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
Labels: autorelease, merge when ready

#449 fix toString typo
  dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java
Labels: merge when ready, no changelog

#451 simulate one big spike of requests
  simulation/src/main/java/com/palantir/dialogue/core/SimulationUtils.java
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_big_spike[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_BLACKLIST_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_big_spike[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_big_spike[UNLIMITED_ROUND_ROBIN].txt
Labels: merge when ready, no changelog

#454 UnknownRemoteException
  changelog/@unreleased/pr-454.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultErrorDecoder.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultErrorDecoderTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/RemoteExceptions.java
  dialogue-target/src/test/java/com/palantir/dialogue/RemoteExceptionsTest.java
Labels: autorelease, merge when ready

#461 Use SafeThreadLocalRandom from separate project
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/SafeThreadLocalRandom.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/SafeThreadLocalRandomTest.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog
