Repository palantir/dialogue, pull requests merged in 2021-05, with the labels that each got.

#1231 Enable incremental annotation processing
  changelog/@unreleased/pr-1231.v2.yml
  dialogue-annotations-processor/build.gradle
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/DialogueRequestAnnotationsProcessor.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1233 Support custom encoders for primitive types
  changelog/@unreleased/pr-1233.v2.yml
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/generate/ServiceImplementationGenerator.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyCustomStringParameterEncoder.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyService.java
  dialogue-annotations-processor/src/test/resources/com/palantir/myservice/service/MyServiceDialogueServiceFactory.java.generated
Labels: autorelease, merge when ready

#1236 Simplify annotation service generator
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/generate/ServiceImplementationGenerator.java
Labels: merge when ready, no changelog

#1240 Provide originating element for generated service factory
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/DialogueRequestAnnotationsProcessor.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/format/Goethe.java
Labels: autorelease, merge when ready, no changelog

#1241 Add MultipartRequestBody example.
  README.md
  dialogue-annotations-example/build.gradle
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/MyService.java
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/PutFileRequest.java
  dialogue-annotations-example/src/test/java/com/palantir/myservice/example/MyServiceIntegrationTest.java
Labels: autorelease, merge when ready, no changelog

#1249 Support lists of primitives.
  changelog/@unreleased/pr-1249.v2.yml
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/MyService.java
  dialogue-annotations-example/src/test/java/com/palantir/myservice/example/MyServiceIntegrationTest.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ArgumentType.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ArgumentTypesResolver.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ResolverContext.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/generate/ServiceImplementationGenerator.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyService.java
  dialogue-annotations-processor/src/test/resources/com/palantir/myservice/service/MyServiceDialogueServiceFactory.java.generated
Labels: autorelease, merge when ready

#1255 Manually include annotation processor META-INF files
  dialogue-annotations-processor/build.gradle
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/DialogueRequestAnnotationsProcessor.java
  dialogue-annotations-processor/src/main/resources/META-INF/gradle/incremental.annotation.processors
  dialogue-annotations-processor/src/main/resources/META-INF/services/javax.annotation.processing.Processor
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#1260 Remove the 'UseCallingThreadExecutor' feature flag, feature is always enabled
  changelog/@unreleased/pr-1260.v2.yml
  dialogue-clients/metrics.md
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/UseCallingThreadExecutor.java
  dialogue-serde/src/main/metrics/feature-flag-metrics.yml
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/UseCallingThreadExecutorTest.java
Labels: autorelease, merge when ready

#1257 Add methods to create channels/clients from ClientConfiguration.
  changelog/1.130.0-rc1/pr-1257.v2.yml
  changelog/@unreleased/pr-1257.v2.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DialogueClients.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
Labels: autorelease, merge when ready

#1266 Add new service-mesh header names to error diagnostics
  changelog/@unreleased/pr-1266.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoder.java
Labels: autorelease, merge when ready

#1269 Rename disabled error decoder.
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/DisabledErrorDecoder.java
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/MyService.java
Labels: merge when ready, no changelog

#1270 Expose DisabledErrorDecoder to consumers
  changelog/@unreleased/pr-1270.v2.yml
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/DisabledErrorDecoder.java
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/MyService.java
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/ErrorDecoder.java
Labels: autorelease, merge when ready

#1272 Dialogue requires Java 11
  build.gradle
  changelog/@unreleased/pr-1272.v2.yml
  dialogue-annotations-example/build.gradle
  dialogue-annotations-processor/build.gradle
  dialogue-annotations-processor/src/test/java/com/palantir/dialogue/annotations/processor/DialogueRequestAnnotationsProcessorTest.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/CleanerSupport.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ResponseLeakDetector.java
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/CleanerSupportTest.java
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ResponseLeakDetectorTest.java
  dialogue-java-client/build.gradle
Labels: autorelease, merge when ready
