Repository palantir/dialogue, pull requests merged in 2021-03, with the labels that each got.

#1137 Blocking clients use the calling thread executor by default
  changelog/@unreleased/pr-1137.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/UseCallingThreadExecutor.java
Labels: autorelease, merge when ready

#1138 Annotation based solution to avoid static method string matching
  changelog/@unreleased/pr-1138.v2.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/Reflection.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/ReflectionTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/DialogueService.java
  dialogue-target/src/main/java/com/palantir/dialogue/DialogueServiceFactory.java
Labels: autorelease, merge when ready

#1144 fix #1143: Gracefully handle service names which aren't valid agents
  changelog/@unreleased/pr-1144.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/UserAgentEndpointChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/UserAgentEndpointChannelTest.java
Labels: autorelease, merge when ready

#1145 Use SOURCE retention for immutables style annotations
  dialogue-apache-hc5-client/build.gradle
  dialogue-clients/build.gradle
  dialogue-core/build.gradle
  dialogue-jmh/build.gradle
  dialogue-serde/build.gradle
  dialogue-target/src/main/java/com/palantir/dialogue/DialogueImmutablesStyle.java
  simulation/build.gradle
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#1148 Dialogue produces a safe NPE when null values are received
  changelog/@unreleased/pr-1148.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/Encodings.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/EncodingsTest.java
Labels: autorelease, merge when ready

#1155 Use more specific generic type arguments to bound serializer factories
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/DeserializerFactory.java
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/Json.java
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/SerializerFactory.java
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/StdDeserializer.java
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/StdSerializer.java
Labels: merge when ready

#1150 Fix #1149: Network failures while writing request bytes are retried
  .palantir/revapi.yml
  changelog/@unreleased/pr-1150.v2.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelTest.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/Encoding.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/Encodings.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/LazilyInitializedEncoding.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/TracedEncoding.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/EncodingsTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/TracedEncodingTest.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractSampleServiceClientTest.java
Labels: autorelease, merge when ready

#1135 Annotation based Dialogue clients API.
  changelog/@unreleased/pr-1135.v2.yml
  dialogue-annotations-processor/build.gradle
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/CustomStringDeserializer.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyCustomParamType.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyResponseDeserializer.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MySerializableType.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MySerializableTypeBodySerializer.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyService.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyServiceDialogueServiceFactory.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyServiceTest.java
  dialogue-annotations/build.gradle
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/DeserializerFactory.java
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/Json.java
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/Request.java
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/SerializerFactory.java
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/StdDeserializer.java
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/StdSerializer.java
  settings.gradle
Labels: autorelease, merge when ready

#1170 Wiring annotation processor and javapoet.
  build.gradle
  dialogue-annotations-processor/build.gradle
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/DialogueAnnotationsProcessor.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/DialogueServiceFactoryGenerator.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/util/Goethe.java
  dialogue-annotations-processor/src/test/java/com/palantir/dialogue/annotations/processor/DialogueAnnotationsProcessorTest.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyServiceDialogueServiceFactory.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyServiceIntegrationTest.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/RequestAnnotatedClass.java
  dialogue-annotations-processor/src/test/resources/com/palantir/myservice/service/MyServiceDialogueServiceFactory.java.generated
  dialogue-annotations-processor/src/testCases/java/com/palantir/myservice/service/CustomStringDeserializer.java
  dialogue-annotations-processor/src/testCases/java/com/palantir/myservice/service/MyCustomParamType.java
  dialogue-annotations-processor/src/testCases/java/com/palantir/myservice/service/MyResponseDeserializer.java
  dialogue-annotations-processor/src/testCases/java/com/palantir/myservice/service/MySerializableType.java
  dialogue-annotations-processor/src/testCases/java/com/palantir/myservice/service/MySerializableTypeBodySerializer.java
  dialogue-annotations-processor/src/testCases/java/com/palantir/myservice/service/MyService.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#1179 Fix testing setup for annotation processor.
  dialogue-annotations-example/build.gradle
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/CustomStringDeserializer.java
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/MyCustomParamType.java
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/MyResponseDeserializer.java
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/MySerializableType.java
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/MySerializableTypeBodySerializer.java
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/MyService.java
  dialogue-annotations-example/src/test/java/com/palantir/myservice/example/MyServiceIntegrationTest.java
  dialogue-annotations-processor/build.gradle
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/DialogueAnnotationsProcessor.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/DialogueRequestAnnotationsProcessor.java
  dialogue-annotations-processor/src/test/java/com/palantir/dialogue/annotations/processor/DialogueRequestAnnotationsProcessorTest.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/CustomStringDeserializer.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyCustomParamType.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyResponseDeserializer.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MySerializableType.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MySerializableTypeBodySerializer.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyService.java
  settings.gradle
Labels: autorelease, do not autorelease, merge when ready, no changelog

#1180 Generate service implementation with method stubs.
  dialogue-annotations-example/build.gradle
  dialogue-annotations-processor/build.gradle
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/DialogueRequestAnnotationsProcessor.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/DialogueServiceFactoryGenerator.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/ErrorContext.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ArgumentDefinition.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ArgumentName.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/EndpointDefinition.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/EndpointDefinitions.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/EndpointName.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/HttpPath.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ParameterType.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ServiceDefinition.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/Type.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/generate/DialogueServiceFactoryGenerator.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/generate/ServiceImplementationGenerator.java
  dialogue-annotations-processor/src/test/java/com/palantir/dialogue/annotations/processor/DialogueRequestAnnotationsProcessorTest.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MultipleParamAnnotations.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/UnparseableHttpPath.java
  dialogue-annotations-processor/src/test/resources/com/palantir/myservice/service/MyServiceDialogueServiceFactory.java.generated
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog
