Repository palantir/dialogue, pull requests merged in 2021-07, with the labels that each got.

#1304 Reword the DialogueException message
  changelog/@unreleased/pr-1304.v2.yml
  dialogue-target/src/main/java/com/palantir/dialogue/DialogueException.java
Labels: autorelease, merge when ready

#1307 Concurrency limiter uses #compareAndSet.
  changelog/@unreleased/pr-1307.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/CautiousIncreaseAggressiveDecreaseConcurrencyLimiter.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/CautiousIncreaseAggressiveDecreaseConcurrencyLimiterTest.java
Labels: autorelease, merge when ready

#1316 LimitedChannel supports disabling limit enforcement.
  changelog/@unreleased/pr-1316.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/CautiousIncreaseAggressiveDecreaseConcurrencyLimiter.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ChannelToLimitedChannelAdapter.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Config.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/LimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NeverThrowLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/SupplierChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ZeroUriNodeSelectionChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/CautiousIncreaseAggressiveDecreaseConcurrencyLimiterTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/NodeSelectionStrategyChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
  dialogue-jmh/src/main/java/com/palantir/dialogue/core/NodeSelectionBenchmark.java
Labels: merge when ready

#1319 Remove jcenter references
  build.gradle
Labels: merge when ready, no changelog

#1320 Simplify code formatting with Goethe
  changelog/@unreleased/pr-1320.v2.yml
  dialogue-annotations-processor/build.gradle
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/DialogueRequestAnnotationsProcessor.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/format/Goethe.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1336 Sticky host routing.
  changelog/@unreleased/pr-1336.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedScoreTracker.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/StickyAttachments.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/NodeSelectionStrategyChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannelTest.java
Labels: merge when ready

#1334 Sticky channels and queue override
  .palantir/revapi.yml
  README.md
  changelog/@unreleased/pr-1334.v2.yml
  dialogue-clients/build.gradle
  dialogue-clients/metrics.md
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DialogueClients.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsIntegrationTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/CautiousIncreaseAggressiveDecreaseConcurrencyLimiter.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueueAttachments.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueueOverrideChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/StickyAttachments.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/StickyConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/StickyEndpointChannels2.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/StickyValidationChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/CautiousIncreaseAggressiveDecreaseConcurrencyLimiterTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueueOverrideChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/StickyAttachmentsTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/StickyConcurrencyLimitedChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/StickyEndpointChannels2Test.java
  dialogue-example/src/main/conjure/example.yml
  simulation/src/test/java/com/palantir/dialogue/core/SimulationTest.java
  simulation/src/test/java/com/palantir/dialogue/core/Strategy.java
  simulation/src/test/resources/report.md
  simulation/src/test/resources/server_side_rate_limits_with_sticky_clients_fairness_across_multiple_clients[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/server_side_rate_limits_with_sticky_clients_fairness_across_multiple_clients[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/server_side_rate_limits_with_sticky_clients_fairness_across_multiple_clients[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/server_side_rate_limits_with_sticky_clients_steady_vs_bursty_client[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/server_side_rate_limits_with_sticky_clients_steady_vs_bursty_client[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/server_side_rate_limits_with_sticky_clients_steady_vs_bursty_client[UNLIMITED_ROUND_ROBIN].png
  simulation/src/test/resources/txt/server_side_rate_limits_with_sticky_clients_fairness_across_multiple_clients[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/server_side_rate_limits_with_sticky_clients_fairness_across_multiple_clients[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/server_side_rate_limits_with_sticky_clients_fairness_across_multiple_clients[UNLIMITED_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/server_side_rate_limits_with_sticky_clients_steady_vs_bursty_client[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/server_side_rate_limits_with_sticky_clients_steady_vs_bursty_client[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/server_side_rate_limits_with_sticky_clients_steady_vs_bursty_client[UNLIMITED_ROUND_ROBIN].txt
Labels: autorelease, merge when ready

#1340 Run the SafeLogger migration manually
  changelog/@unreleased/pr-1340.v2.yml
  dialogue-annotations/build.gradle
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/InputStreamContentBody.java
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/MultipartRequestBody.java
  dialogue-apache-hc5-client/build.gradle
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InactivityValidationAwareConnectionKeepAliveStrategy.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ResponseLeakDetector.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ScheduledIdleConnectionEvictor.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ServerTimingParser.java
  dialogue-blocking-channels/build.gradle
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/BlockingChannelAdapter.java
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/DefaultCallingThreadExecutor.java
  dialogue-client-verifier/build.gradle
  dialogue-client-verifier/src/test/java/com/palantir/verification/AutoDeserializeTest.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/SingleParamServicesTest.java
  dialogue-client-verifier/src/test/java/com/palantir/verification/VerificationServerRule.java
  dialogue-clients/build.gradle
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelCache.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/Reflection.java
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/BalancedScoreTracker.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/CautiousIncreaseAggressiveDecreaseConcurrencyLimiter.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ContentDecodingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DeprecationWarningChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueNodeSelectionStrategy.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NeverThrowChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NeverThrowEndpointChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NeverThrowLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryOtherValidatingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/StickyConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TimingEndpointChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/UserAgentEndpointChannel.java
  dialogue-futures/build.gradle
  dialogue-futures/src/main/java/com/palantir/dialogue/futures/SafeDirectExecutor.java
  dialogue-httpurlconnection-client/build.gradle
  dialogue-httpurlconnection-client/src/main/java/com/palantir/dialogue/httpurlconnection/HttpUrlConnectionBlockingChannel.java
  dialogue-java-client/build.gradle
  dialogue-java-client/src/main/java/com/palantir/dialogue/HttpChannel.java
  dialogue-okhttp-client/build.gradle
  dialogue-okhttp-client/src/main/java/com/palantir/dialogue/OkHttpChannels.java
  dialogue-serde/build.gradle
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoder.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/JacksonEmptyContainerLoader.java
  dialogue-target/build.gradle
  simulation/build.gradle
  simulation/src/main/java/com/palantir/dialogue/core/Simulation.java
  versions.lock
Labels: autorelease, merge when ready
