Repository palantir/dialogue, pull requests merged in 2021-02, with the labels that each got.

#1107 Introduce attachments to Request API.
  changelog/1.97.0-rc1/pr-1107.v2.yml
  changelog/@unreleased/pr-1107.v2.yml
  dialogue-target/build.gradle
  dialogue-target/src/main/java/com/palantir/dialogue/Request.java
  dialogue-target/src/main/java/com/palantir/dialogue/RequestAttachmentKey.java
  dialogue-target/src/main/java/com/palantir/dialogue/RequestAttachments.java
  dialogue-target/src/test/java/com/palantir/dialogue/RequestAttachmentsTest.java
Labels: autorelease, merge when ready

#1111 TraceEnrichingChannel uses the traceId from TraceMetadata
  changelog/@unreleased/pr-1111.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/TraceEnrichingChannel.java
Labels: autorelease, merge when ready

#1112 Simplifications from a read-through
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/BlockingChannelAdapter.java
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/CallingThreadExecutor.java
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/DefaultCallingThreadExecutor.java
  dialogue-blocking-channels/src/test/java/com/palantir/dialogue/blocking/DefaultCallingThreadExecutorTest.java
Labels: merge when ready

#1109 Clients#callBlocking now uses the calling thread for network calls.
  changelog/1.97.0-rc1/pr-1107.v2.yml
  changelog/@unreleased/pr-1090.v2.yml
  dialogue-blocking-channels/build.gradle
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/BlockingChannelAdapter.java
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/CallingThreadExecutor.java
  dialogue-blocking-channels/src/main/java/com/palantir/dialogue/blocking/DefaultCallingThreadExecutor.java
  dialogue-blocking-channels/src/test/java/com/palantir/dialogue/blocking/DefaultCallingThreadExecutorTest.java
  dialogue-serde/build.gradle
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultClients.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/UseCallingThreadExecutor.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsTest.java
  dialogue-serde/src/test/java/com/palantir/dialogue/blocking/CallingThreadExecutorAssert.java
Labels: autorelease, merge when ready

#1114 Disable the markdown check to allow builds when unrelated sites have outages
  .circleci/config.yml
Labels: merge when ready, no changelog

#1113 Enable CallingThreadExecutor for 1% of traffic.
  changelog/@unreleased/pr-1113.v2.yml
  dialogue-clients/metrics.md
  dialogue-serde/build.gradle
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/UseCallingThreadExecutor.java
  dialogue-serde/src/main/metrics/feature-flag-metrics.yml
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/UseCallingThreadExecutorTest.java
Labels: autorelease, merge when ready

#1132 Dialogue client exceptions are given additional diagnostic arguments
  changelog/@unreleased/pr-1132.v2.yml
  dialogue-apache-hc5-client/build.gradle
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ApacheHttpClientChannelsTest.java
Labels: autorelease, merge when ready

#1134 Downgrade Caffeine cache to 2.9.0 to avoid a java 11 requirement
  changelog/@unreleased/pr-1134.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready
