Repository palantir/dialogue, pull requests merged in 2022-02, with the labels that each got.

#1570 Sticky fixes 2
  changelog/@unreleased/pr-1570.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/StickyEndpointChannels2.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/StickyEndpointChannels2Test.java
Labels: merge when ready, autorelease

#1578 Check before allocating args for debug logging
  changelog/@unreleased/pr-1578.v2.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/Reflection.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/UserAgentEndpointChannel.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/JacksonEmptyContainerLoader.java
Labels: merge when ready, autorelease

#1583 InstrumentedDnsResolver debug logging includes the client name
  changelog/@unreleased/pr-1583.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedDnsResolver.java
Labels: merge when ready

#1582 Track host resolution failure metrics
  changelog/@unreleased/pr-1582.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedDnsResolver.java
  dialogue-apache-hc5-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ApacheHttpClientChannelsTest.java
  dialogue-clients/metrics.md
Labels: merge when ready, autorelease

#1584 Reduce unnecessary `Arg` creation in happy paths
  changelog/@unreleased/pr-1584.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/BaseUrl.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/MeshMode.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/PinUntilErrorNodeSelectionStrategyChannel.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/JacksonEmptyContainerLoader.java
  dialogue-target/src/main/java/com/palantir/dialogue/PathTemplate.java
  dialogue-target/src/main/java/com/palantir/dialogue/TypeMarker.java
Labels: merge when ready, autorelease

#1585 Add metric for no route to host errors
  changelog/@unreleased/pr-1585.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedPoolingHttpClientConnectionManager.java
  dialogue-apache-hc5-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ApacheHttpClientChannelsTest.java
  dialogue-clients/metrics.md
Labels: merge when ready, autorelease

#1586 Dialogue request and response serializers are cached
  changelog/@unreleased/pr-1586.v2.yml
  dialogue-serde/build.gradle
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultConjureRuntime.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/BinaryEncodingTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDeTest.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/DefaultClientsTest.java
  dialogue-target/src/main/java/com/palantir/dialogue/TypeMarker.java
Labels: merge when ready, autorelease

#1596 Update comment regarding HTTP method retries
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
Labels: merge when ready, no changelog, autorelease

#1607 Optimize tracingTags for TracedChannel & DialogueTracing
  changelog/@unreleased/pr-1607.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueTracing.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TracedChannel.java
Labels: merge when ready, autorelease

#1606 Detect usage of deprecated cipher suites
  changelog/@unreleased/pr-1606.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedHostnameVerifier.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedPoolingHttpClientConnectionManager.java
  dialogue-apache-hc5-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ApacheHttpClientChannelsTest.java
  dialogue-clients/metrics.md
  versions.lock
  versions.props
Labels: merge when ready, autorelease

#1609 Delete the undocumented `dialogueVersion` metric tag
  changelog/@unreleased/pr-1609.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/Config.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/VersionedTaggedMetricRegistry.java
Labels: merge when ready, autorelease
