Repository palantir/dialogue, pull requests merged in 2024-11, with the labels that each got.

#2398 Optimize target selection and URI parsing
  changelog/@unreleased/pr-2398.v2.yml
  dialogue-clients/build.gradle
  dialogue-clients/metrics.md
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DialogueDnsResolutionWorker.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DnsSupport.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/DnsSupportTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueNodeSelectionStrategy.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TargetUri.java
  versions.lock
Labels: merge when ready, autorelease, 🤖 fix nits

#2410 Migrate squareup javapoet to Palantir javapoet
  changelog/@unreleased/pr-2410.v2.yml
  dialogue-annotations-processor/build.gradle
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/DialogueRequestAnnotationsProcessor.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ArgumentType.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ArgumentTypesResolver.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ParamTypesResolver.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ParameterEncoderType.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ParameterType.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ResolverContext.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ReturnType.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ReturnTypesResolver.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ServiceDefinition.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/generate/DialogueServiceFactoryGenerator.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/generate/EndpointsEnumGenerator.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/generate/ServiceImplementationGenerator.java
  dialogue-annotations-processor/src/test/java/com/palantir/dialogue/annotations/processor/data/ArgumentTypesResolverTest.java
  versions.lock
  versions.props
Labels: merge when ready

#2412 Config.uris uses `toList()` collector
  dialogue-core/src/main/java/com/palantir/dialogue/core/Config.java
Labels: merge when ready, no changelog

#2422 QueuedChannel enforces its assumption around at least one in-flight request
  changelog/@unreleased/pr-2422.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java
  dialogue-core/src/test/resources/tracing/QueuedChannelTest/testQueueTracing.log
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/report.md
  simulation/src/test/resources/server_side_rate_limits[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/server_side_rate_limits[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].png
  simulation/src/test/resources/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].png
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/all_nodes_500[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/one_endpoint_dies_on_each_server[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/server_side_rate_limits[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/server_side_rate_limits[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_PIN_UNTIL_ERROR].txt
  simulation/src/test/resources/txt/slowdown_and_error_thresholds[CONCURRENCY_LIMITER_ROUND_ROBIN].txt
Labels: merge when ready

#2418 Retain endpoint concurrency limits on node refresh
  changelog/@unreleased/pr-2418.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/ConcurrencyLimitedChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ConcurrencyLimitedChannelTest.java
Labels: merge when ready, autorelease

#2434 Implement the `Client-Can-Retry: true` hint header for reverse proxies
  changelog/@unreleased/pr-2434.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryAdvertisementChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryAdvertisementChannelTest.java
Labels: merge when ready

#2430 Implement support for the Proxy-Upstream-Request-Attempts header
  changelog/@unreleased/pr-2430.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/Responses.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ResponsesTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
Labels: merge when ready, autorelease
