Repository palantir/dialogue, pull requests merged in 2024-01, with the labels that each got.

#2093 Add reason to propagated QoS errors
  changelog/@unreleased/pr-2093.v2.yml
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoder.java
  dialogue-serde/src/test/java/com/palantir/conjure/java/dialogue/serde/ErrorDecoderTest.java
Labels: merge when ready, autorelease

#2094 Simplify InstrumentedSslConnectionSocketFactory
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedSslConnectionSocketFactory.java
Labels: merge when ready, no changelog, autorelease

#2114 Handle ETIMEDOUT SocketExceptions
  changelog/@unreleased/pr-2114.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryingChannelTest.java
Labels: merge when ready, autorelease

#2116 Wire up orphaned AbstractSampleServiceClientTest
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ApacheSampleServiceClientTest.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractSampleServiceClientTest.java
Labels: merge when ready, no changelog
