Repository palantir/dialogue, pull requests merged in 2024-05, with the labels that each got.

#2263 Dialogue fails fast when existing channels are revoked from DNS
  changelog/@unreleased/pr-2263.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/SafeConnectException.java
  dialogue-apache-hc5-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-clients/metrics.md
Labels: merge when ready, autorelease

#2268 Revert "Dialogue fails fast when existing channels are revoked from DNS"
  changelog/@unreleased/pr-2268.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/SafeConnectException.java
  dialogue-apache-hc5-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-clients/metrics.md
Labels: merge when ready, autorelease

#2273 Reduce the default DNS poll interval from 5 seconds to 1
  changelog/@unreleased/pr-2273.v2.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
Labels: merge when ready

#2269 Refactor DNS-based channel refresh within DialogueChannel
  changelog/@unreleased/pr-2269.v2.yml
  dialogue-clients/metrics.md
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelCache.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DnsPollingSpec.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DnsSupport.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/DialogueClientsDnsIntegrationTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/DialogueDnsResolutionWorkerTest.java
  dialogue-core/build.gradle
  dialogue-core/src/main/java/com/palantir/dialogue/core/Config.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ContentDecodingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/NodeSelectionStrategyChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/SafeUnknownHostException.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ZeroUriNodeSelectionChannel.java
  dialogue-core/src/main/metrics/dialogue-core-metrics.yml
  dialogue-core/src/test/java/com/palantir/dialogue/core/ContentDecodingChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DialogueChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/HostMetricsChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RequestSizeMetricsChannelTest.java
Labels: merge when ready, autorelease

#2274 Avoid expensive refreshable creation in a potentially hot path
  changelog/@unreleased/pr-2274.v2.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ContentDecodingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
Labels: merge when ready, autorelease

#2275 [tests only] Add test coverage for perHost dns refresh memory management
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/DialogueClientsDnsIntegrationTest.java
Labels: merge when ready, no changelog

#2276 RetryOtherValidatingChannel handles mesh URIs
  changelog/@unreleased/pr-2276.v2.yml
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsIntegrationTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Config.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/RetryOtherValidatingChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/HostMetricsChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RequestSizeMetricsChannelTest.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/RetryOtherValidatingChannelTest.java
Labels: merge when ready, autorelease

#2277 DefaultDialogueDnsResolver logs UnknownHostException at debug
  changelog/@unreleased/pr-2277.v2.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DefaultDialogueDnsResolver.java
Labels: merge when ready, autorelease

#2279 Add support for routing through an HTTPS proxy
  changelog/@unreleased/pr-2279.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/DialogueRoutePlanner.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/HttpsProxyDefaultRoutePlanner.java
  dialogue-test-common/src/main/java/com/palantir/dialogue/AbstractProxyConfigTlsTest.java
  versions.lock
  versions.props
Labels: merge when ready, autorelease

#2281 feature: add support for HeaderMap
  README.md
  dialogue-annotations-example/src/main/java/com/palantir/myservice/example/MyService.java
  dialogue-annotations-example/src/test/java/com/palantir/myservice/example/MyServiceIntegrationTest.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ParamTypesResolver.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/data/ParameterType.java
  dialogue-annotations-processor/src/main/java/com/palantir/dialogue/annotations/processor/generate/ServiceImplementationGenerator.java
  dialogue-annotations-processor/src/test/java/com/palantir/myservice/service/MyService.java
  dialogue-annotations-processor/src/test/resources/com/palantir/myservice/service/MyServiceDialogueServiceFactory.java.generated
  dialogue-annotations/src/main/java/com/palantir/dialogue/annotations/Request.java
Labels: merge when ready, no changelog, autorelease

#2283 CachingFallbackDnsResolver logs at debug level
  changelog/@unreleased/pr-2283.v2.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/CachingFallbackDnsResolver.java
Labels: merge when ready, autorelease
