Repository palantir/dialogue, pull requests merged in 2024-02, with the labels that each got.

#2134 Dialogue client channel creation may target a specific address
  .palantir/revapi.yml
  changelog/@unreleased/pr-2134.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientBlockingChannel.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/DialogueRoutePlanner.java
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ResolvedAddressTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannelFactory.java
  dialogue-test-common/build.gradle
  dialogue-test-common/src/main/java/com/palantir/dialogue/TestOnlyCertificates.java
  versions.lock
  versions.props
Labels: merge when ready, autorelease

#2140 Implement a DNS resolver facade within Dialogue
  .palantir/revapi.yml
  changelog/@unreleased/pr-2140.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedDnsResolver.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelCache.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DefaultDialogueDnsResolver.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DialogueClients.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/ChannelCacheTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/DefaultDialogueDnsResolverTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsDnsIntegrationTest.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueDnsResolver.java
Labels: merge when ready

#2144 [feature/dns] don't tag changes with autorelease
  .github/autolabeler.yml
Labels: merge when ready, no changelog

#2143 [feature/dns] Plumb resolved address data through to clients
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelCache.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Config.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TargetUri.java
Labels: merge when ready

#2141 WIP dns resolution worker v2
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DialogueClients.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DialogueDnsResolutionWorker.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ServicesConfigBlockWithResolvedHosts.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/DialogueDnsResolutionWorkerTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsTest.java
Labels: no changelog

#2165 Implement DNS-based node discovery
  .palantir/revapi.yml
  changelog/@unreleased/pr-2165.v2.yml
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ApacheHttpClientChannels.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/ConnectInstrumentation.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/DialogueRoutePlanner.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedPlainConnectionSocketFactory.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedPoolingHttpClientConnectionManager.java
  dialogue-apache-hc5-client/src/main/java/com/palantir/dialogue/hc5/InstrumentedSslConnectionSocketFactory.java
  dialogue-apache-hc5-client/src/main/metrics/dialogue-apache-client-metrics.yml
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ApacheHttpClientChannelsTest.java
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ResolvedAddressTest.java
  dialogue-clients/build.gradle
  dialogue-clients/metrics.md
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelCache.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DialogueClients.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DialogueDnsResolutionWorker.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DnsPollingSpec.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DnsResolutionResults.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DnsSupport.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ProtocolVersionFilteringDialogueDnsResolver.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/main/metrics/dialogue-core-metrics.yml
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/DialogueClientsDnsIntegrationTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/DialogueDnsResolutionWorkerTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/ProtocolVersionFilteringDialogueDnsResolverTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsDnsIntegrationTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsIntegrationTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/otherpackage/DialogueClientsTest.java
  dialogue-clients/src/test/java/com/palantir/dialogue/util/MapBasedDnsResolver.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/Config.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/ContentDecodingChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/DialogueChannel.java
  dialogue-core/src/main/java/com/palantir/dialogue/core/TargetUri.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/ContentDecodingChannelTest.java
  dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/DefaultConjureRuntime.java
Labels: merge when ready, autorelease

#2171 handle invalid URIs
  changelog/@unreleased/pr-2171.v2.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/DialogueClientsDnsIntegrationTest.java
Labels: merge when ready, autorelease

#2174 Use the 'channel-name' tag to avoid overloading 'service'
  dialogue-clients/metrics.md
  dialogue-clients/src/main/metrics/dialogue-core-metrics.yml
Labels: merge when ready, no changelog, autorelease

#2176 Implement a DNS fallback cache to avoid failures in DNS outages
  changelog/@unreleased/pr-2176.v2.yml
  dialogue-clients/metrics.md
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/CachingFallbackDnsResolver.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/main/metrics/dialogue-core-metrics.yml
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/CachingFallbackDnsResolverTest.java
Labels: merge when ready, autorelease

#2179 add more specific metrics and logging for DNS lookup failures
  changelog/@unreleased/pr-2179.v2.yml
  dialogue-clients/metrics.md
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/DefaultDialogueDnsResolver.java
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java
  dialogue-clients/src/main/metrics/dialogue-core-metrics.yml
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/DefaultDialogueDnsResolverTest.java
Labels: merge when ready, autorelease
