Repository palantir/dialogue, pull requests merged in 2025-07, with the labels that each got.

#2605 Refactor `ApacheHttpClientChannelsTest#metrics` test to not rely on flaky website
  dialogue-apache-hc5-client/src/test/java/com/palantir/dialogue/hc5/ApacheHttpClientChannelsTest.java
Labels: merge when ready, no changelog

#2604 Return a failed future on deadline expiration
  changelog/@unreleased/pr-2604.v2.yml
  dialogue-core/src/main/java/com/palantir/dialogue/core/DeadlineAdvertisementChannel.java
  dialogue-core/src/test/java/com/palantir/dialogue/core/DeadlineAdvertisementChannelTest.java
Labels: autorelease, 🤖 fix nits

#2629 More descriptive channel names for enabled/disabled params
  changelog/@unreleased/pr-2629.v2.yml
  dialogue-clients/src/main/java/com/palantir/dialogue/clients/ChannelNames.java
  dialogue-clients/src/test/java/com/palantir/dialogue/clients/ChannelNamesTest.java
Labels: autorelease
